// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pikasa/insights/v1/insights.proto

package insightsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/pikasaco/pikasa-go/pikasa/insights/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// InsightsServiceName is the fully-qualified name of the InsightsService service.
	InsightsServiceName = "pikasa.insights.v1.InsightsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// InsightsServiceGetMarketStatsProcedure is the fully-qualified name of the InsightsService's
	// GetMarketStats RPC.
	InsightsServiceGetMarketStatsProcedure = "/pikasa.insights.v1.InsightsService/GetMarketStats"
)

// InsightsServiceClient is a client for the pikasa.insights.v1.InsightsService service.
type InsightsServiceClient interface {
	GetMarketStats(context.Context, *connect.Request[v1.GetMarketStatsRequest]) (*connect.Response[v1.GetMarketStatsResponse], error)
}

// NewInsightsServiceClient constructs a client for the pikasa.insights.v1.InsightsService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewInsightsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) InsightsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	insightsServiceMethods := v1.File_pikasa_insights_v1_insights_proto.Services().ByName("InsightsService").Methods()
	return &insightsServiceClient{
		getMarketStats: connect.NewClient[v1.GetMarketStatsRequest, v1.GetMarketStatsResponse](
			httpClient,
			baseURL+InsightsServiceGetMarketStatsProcedure,
			connect.WithSchema(insightsServiceMethods.ByName("GetMarketStats")),
			connect.WithClientOptions(opts...),
		),
	}
}

// insightsServiceClient implements InsightsServiceClient.
type insightsServiceClient struct {
	getMarketStats *connect.Client[v1.GetMarketStatsRequest, v1.GetMarketStatsResponse]
}

// GetMarketStats calls pikasa.insights.v1.InsightsService.GetMarketStats.
func (c *insightsServiceClient) GetMarketStats(ctx context.Context, req *connect.Request[v1.GetMarketStatsRequest]) (*connect.Response[v1.GetMarketStatsResponse], error) {
	return c.getMarketStats.CallUnary(ctx, req)
}

// InsightsServiceHandler is an implementation of the pikasa.insights.v1.InsightsService service.
type InsightsServiceHandler interface {
	GetMarketStats(context.Context, *connect.Request[v1.GetMarketStatsRequest]) (*connect.Response[v1.GetMarketStatsResponse], error)
}

// NewInsightsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewInsightsServiceHandler(svc InsightsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	insightsServiceMethods := v1.File_pikasa_insights_v1_insights_proto.Services().ByName("InsightsService").Methods()
	insightsServiceGetMarketStatsHandler := connect.NewUnaryHandler(
		InsightsServiceGetMarketStatsProcedure,
		svc.GetMarketStats,
		connect.WithSchema(insightsServiceMethods.ByName("GetMarketStats")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pikasa.insights.v1.InsightsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case InsightsServiceGetMarketStatsProcedure:
			insightsServiceGetMarketStatsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedInsightsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedInsightsServiceHandler struct{}

func (UnimplementedInsightsServiceHandler) GetMarketStats(context.Context, *connect.Request[v1.GetMarketStatsRequest]) (*connect.Response[v1.GetMarketStatsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pikasa.insights.v1.InsightsService.GetMarketStats is not implemented"))
}
