// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pikasa/listings/v1/listings.proto

package listingsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/pikasaco/pikasa-go/pikasa/listings/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ListingsServiceName is the fully-qualified name of the ListingsService service.
	ListingsServiceName = "pikasa.listings.v1.ListingsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ListingsServiceSearchListingsProcedure is the fully-qualified name of the ListingsService's
	// SearchListings RPC.
	ListingsServiceSearchListingsProcedure = "/pikasa.listings.v1.ListingsService/SearchListings"
	// ListingsServiceGetListingProcedure is the fully-qualified name of the ListingsService's
	// GetListing RPC.
	ListingsServiceGetListingProcedure = "/pikasa.listings.v1.ListingsService/GetListing"
)

// ListingsServiceClient is a client for the pikasa.listings.v1.ListingsService service.
type ListingsServiceClient interface {
	SearchListings(context.Context, *connect.Request[v1.SearchListingsRequest]) (*connect.Response[v1.SearchListingsResponse], error)
	GetListing(context.Context, *connect.Request[v1.GetListingRequest]) (*connect.Response[v1.GetListingResponse], error)
}

// NewListingsServiceClient constructs a client for the pikasa.listings.v1.ListingsService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewListingsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ListingsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	listingsServiceMethods := v1.File_pikasa_listings_v1_listings_proto.Services().ByName("ListingsService").Methods()
	return &listingsServiceClient{
		searchListings: connect.NewClient[v1.SearchListingsRequest, v1.SearchListingsResponse](
			httpClient,
			baseURL+ListingsServiceSearchListingsProcedure,
			connect.WithSchema(listingsServiceMethods.ByName("SearchListings")),
			connect.WithClientOptions(opts...),
		),
		getListing: connect.NewClient[v1.GetListingRequest, v1.GetListingResponse](
			httpClient,
			baseURL+ListingsServiceGetListingProcedure,
			connect.WithSchema(listingsServiceMethods.ByName("GetListing")),
			connect.WithClientOptions(opts...),
		),
	}
}

// listingsServiceClient implements ListingsServiceClient.
type listingsServiceClient struct {
	searchListings *connect.Client[v1.SearchListingsRequest, v1.SearchListingsResponse]
	getListing     *connect.Client[v1.GetListingRequest, v1.GetListingResponse]
}

// SearchListings calls pikasa.listings.v1.ListingsService.SearchListings.
func (c *listingsServiceClient) SearchListings(ctx context.Context, req *connect.Request[v1.SearchListingsRequest]) (*connect.Response[v1.SearchListingsResponse], error) {
	return c.searchListings.CallUnary(ctx, req)
}

// GetListing calls pikasa.listings.v1.ListingsService.GetListing.
func (c *listingsServiceClient) GetListing(ctx context.Context, req *connect.Request[v1.GetListingRequest]) (*connect.Response[v1.GetListingResponse], error) {
	return c.getListing.CallUnary(ctx, req)
}

// ListingsServiceHandler is an implementation of the pikasa.listings.v1.ListingsService service.
type ListingsServiceHandler interface {
	SearchListings(context.Context, *connect.Request[v1.SearchListingsRequest]) (*connect.Response[v1.SearchListingsResponse], error)
	GetListing(context.Context, *connect.Request[v1.GetListingRequest]) (*connect.Response[v1.GetListingResponse], error)
}

// NewListingsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewListingsServiceHandler(svc ListingsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	listingsServiceMethods := v1.File_pikasa_listings_v1_listings_proto.Services().ByName("ListingsService").Methods()
	listingsServiceSearchListingsHandler := connect.NewUnaryHandler(
		ListingsServiceSearchListingsProcedure,
		svc.SearchListings,
		connect.WithSchema(listingsServiceMethods.ByName("SearchListings")),
		connect.WithHandlerOptions(opts...),
	)
	listingsServiceGetListingHandler := connect.NewUnaryHandler(
		ListingsServiceGetListingProcedure,
		svc.GetListing,
		connect.WithSchema(listingsServiceMethods.ByName("GetListing")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pikasa.listings.v1.ListingsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ListingsServiceSearchListingsProcedure:
			listingsServiceSearchListingsHandler.ServeHTTP(w, r)
		case ListingsServiceGetListingProcedure:
			listingsServiceGetListingHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedListingsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedListingsServiceHandler struct{}

func (UnimplementedListingsServiceHandler) SearchListings(context.Context, *connect.Request[v1.SearchListingsRequest]) (*connect.Response[v1.SearchListingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pikasa.listings.v1.ListingsService.SearchListings is not implemented"))
}

func (UnimplementedListingsServiceHandler) GetListing(context.Context, *connect.Request[v1.GetListingRequest]) (*connect.Response[v1.GetListingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pikasa.listings.v1.ListingsService.GetListing is not implemented"))
}
