// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pikasa/insights/v1/insights.proto

package insightsv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/pikasaco/pikasa-go/pikasa/listings/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMarketStatsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CountryCode     string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Admin2          string                 `protobuf:"bytes,2,opt,name=admin2,proto3" json:"admin2,omitempty"`                                                                                   // city, required
	PropertyType    v1.PropertyType        `protobuf:"varint,3,opt,name=property_type,json=propertyType,proto3,enum=pikasa.listings.v1.PropertyType" json:"property_type,omitempty"`             // required (not UNSPECIFIED)
	TransactionType v1.TransactionType     `protobuf:"varint,4,opt,name=transaction_type,json=transactionType,proto3,enum=pikasa.listings.v1.TransactionType" json:"transaction_type,omitempty"` // required (sale or rent)
	Months          int32                  `protobuf:"varint,5,opt,name=months,proto3" json:"months,omitempty"`                                                                                  // 0 → default 12
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetMarketStatsRequest) Reset() {
	*x = GetMarketStatsRequest{}
	mi := &file_pikasa_insights_v1_insights_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketStatsRequest) ProtoMessage() {}

func (x *GetMarketStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_insights_v1_insights_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketStatsRequest.ProtoReflect.Descriptor instead.
func (*GetMarketStatsRequest) Descriptor() ([]byte, []int) {
	return file_pikasa_insights_v1_insights_proto_rawDescGZIP(), []int{0}
}

func (x *GetMarketStatsRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *GetMarketStatsRequest) GetAdmin2() string {
	if x != nil {
		return x.Admin2
	}
	return ""
}

func (x *GetMarketStatsRequest) GetPropertyType() v1.PropertyType {
	if x != nil {
		return x.PropertyType
	}
	return v1.PropertyType(0)
}

func (x *GetMarketStatsRequest) GetTransactionType() v1.TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return v1.TransactionType(0)
}

func (x *GetMarketStatsRequest) GetMonths() int32 {
	if x != nil {
		return x.Months
	}
	return 0
}

type MonthlyStat struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Month            string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"` // "2026-05"
	MedianPricePerM2 float64                `protobuf:"fixed64,2,opt,name=median_price_per_m2,json=medianPricePerM2,proto3" json:"median_price_per_m2,omitempty"`
	ObservationCount int32                  `protobuf:"varint,3,opt,name=observation_count,json=observationCount,proto3" json:"observation_count,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MonthlyStat) Reset() {
	*x = MonthlyStat{}
	mi := &file_pikasa_insights_v1_insights_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyStat) ProtoMessage() {}

func (x *MonthlyStat) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_insights_v1_insights_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyStat.ProtoReflect.Descriptor instead.
func (*MonthlyStat) Descriptor() ([]byte, []int) {
	return file_pikasa_insights_v1_insights_proto_rawDescGZIP(), []int{1}
}

func (x *MonthlyStat) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *MonthlyStat) GetMedianPricePerM2() float64 {
	if x != nil {
		return x.MedianPricePerM2
	}
	return 0
}

func (x *MonthlyStat) GetObservationCount() int32 {
	if x != nil {
		return x.ObservationCount
	}
	return 0
}

func (x *MonthlyStat) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetMarketStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*MonthlyStat         `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"` // oldest first; months without data omitted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketStatsResponse) Reset() {
	*x = GetMarketStatsResponse{}
	mi := &file_pikasa_insights_v1_insights_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketStatsResponse) ProtoMessage() {}

func (x *GetMarketStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_insights_v1_insights_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketStatsResponse.ProtoReflect.Descriptor instead.
func (*GetMarketStatsResponse) Descriptor() ([]byte, []int) {
	return file_pikasa_insights_v1_insights_proto_rawDescGZIP(), []int{2}
}

func (x *GetMarketStatsResponse) GetStats() []*MonthlyStat {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_pikasa_insights_v1_insights_proto protoreflect.FileDescriptor

const file_pikasa_insights_v1_insights_proto_rawDesc = "" +
	"\n" +
	"!pikasa/insights/v1/insights.proto\x12\x12pikasa.insights.v1\x1a\x1bbuf/validate/validate.proto\x1a!pikasa/listings/v1/listings.proto\"\x9f\x02\n" +
	"\x15GetMarketStatsRequest\x12+\n" +
	"\fcountry_code\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x02R\vcountryCode\x12\x1f\n" +
	"\x06admin2\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06admin2\x12E\n" +
	"\rproperty_type\x18\x03 \x01(\x0e2 .pikasa.listings.v1.PropertyTypeR\fpropertyType\x12N\n" +
	"\x10transaction_type\x18\x04 \x01(\x0e2#.pikasa.listings.v1.TransactionTypeR\x0ftransactionType\x12!\n" +
	"\x06months\x18\x05 \x01(\x05B\t\xbaH\x06\x1a\x04\x18\x18(\x00R\x06months\"\x9b\x01\n" +
	"\vMonthlyStat\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12-\n" +
	"\x13median_price_per_m2\x18\x02 \x01(\x01R\x10medianPricePerM2\x12+\n" +
	"\x11observation_count\x18\x03 \x01(\x05R\x10observationCount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"O\n" +
	"\x16GetMarketStatsResponse\x125\n" +
	"\x05stats\x18\x01 \x03(\v2\x1f.pikasa.insights.v1.MonthlyStatR\x05stats2z\n" +
	"\x0fInsightsService\x12g\n" +
	"\x0eGetMarketStats\x12).pikasa.insights.v1.GetMarketStatsRequest\x1a*.pikasa.insights.v1.GetMarketStatsResponseB\xce\x01\n" +
	"\x16com.pikasa.insights.v1B\rInsightsProtoP\x01Z;github.com/pikasaco/pikasa-go/pikasa/insights/v1;insightsv1\xa2\x02\x03PIX\xaa\x02\x12Pikasa.Insights.V1\xca\x02\x12Pikasa\\Insights\\V1\xe2\x02\x1ePikasa\\Insights\\V1\\GPBMetadata\xea\x02\x14Pikasa::Insights::V1b\x06proto3"

var (
	file_pikasa_insights_v1_insights_proto_rawDescOnce sync.Once
	file_pikasa_insights_v1_insights_proto_rawDescData []byte
)

func file_pikasa_insights_v1_insights_proto_rawDescGZIP() []byte {
	file_pikasa_insights_v1_insights_proto_rawDescOnce.Do(func() {
		file_pikasa_insights_v1_insights_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pikasa_insights_v1_insights_proto_rawDesc), len(file_pikasa_insights_v1_insights_proto_rawDesc)))
	})
	return file_pikasa_insights_v1_insights_proto_rawDescData
}

var file_pikasa_insights_v1_insights_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pikasa_insights_v1_insights_proto_goTypes = []any{
	(*GetMarketStatsRequest)(nil),  // 0: pikasa.insights.v1.GetMarketStatsRequest
	(*MonthlyStat)(nil),            // 1: pikasa.insights.v1.MonthlyStat
	(*GetMarketStatsResponse)(nil), // 2: pikasa.insights.v1.GetMarketStatsResponse
	(v1.PropertyType)(0),           // 3: pikasa.listings.v1.PropertyType
	(v1.TransactionType)(0),        // 4: pikasa.listings.v1.TransactionType
}
var file_pikasa_insights_v1_insights_proto_depIdxs = []int32{
	3, // 0: pikasa.insights.v1.GetMarketStatsRequest.property_type:type_name -> pikasa.listings.v1.PropertyType
	4, // 1: pikasa.insights.v1.GetMarketStatsRequest.transaction_type:type_name -> pikasa.listings.v1.TransactionType
	1, // 2: pikasa.insights.v1.GetMarketStatsResponse.stats:type_name -> pikasa.insights.v1.MonthlyStat
	0, // 3: pikasa.insights.v1.InsightsService.GetMarketStats:input_type -> pikasa.insights.v1.GetMarketStatsRequest
	2, // 4: pikasa.insights.v1.InsightsService.GetMarketStats:output_type -> pikasa.insights.v1.GetMarketStatsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pikasa_insights_v1_insights_proto_init() }
func file_pikasa_insights_v1_insights_proto_init() {
	if File_pikasa_insights_v1_insights_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pikasa_insights_v1_insights_proto_rawDesc), len(file_pikasa_insights_v1_insights_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pikasa_insights_v1_insights_proto_goTypes,
		DependencyIndexes: file_pikasa_insights_v1_insights_proto_depIdxs,
		MessageInfos:      file_pikasa_insights_v1_insights_proto_msgTypes,
	}.Build()
	File_pikasa_insights_v1_insights_proto = out.File
	file_pikasa_insights_v1_insights_proto_goTypes = nil
	file_pikasa_insights_v1_insights_proto_depIdxs = nil
}
