// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pikasa/listings/v1/listings.proto

package listingsv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PropertyType int32

const (
	PropertyType_PROPERTY_TYPE_UNSPECIFIED PropertyType = 0
	PropertyType_PROPERTY_TYPE_APARTMENT   PropertyType = 1
	PropertyType_PROPERTY_TYPE_HOUSE       PropertyType = 2
	PropertyType_PROPERTY_TYPE_OFFICE      PropertyType = 3
	PropertyType_PROPERTY_TYPE_LAND        PropertyType = 4
	PropertyType_PROPERTY_TYPE_FARM        PropertyType = 5
	PropertyType_PROPERTY_TYPE_STUDIO      PropertyType = 6
	PropertyType_PROPERTY_TYPE_COMMERCIAL  PropertyType = 7
)

// Enum value maps for PropertyType.
var (
	PropertyType_name = map[int32]string{
		0: "PROPERTY_TYPE_UNSPECIFIED",
		1: "PROPERTY_TYPE_APARTMENT",
		2: "PROPERTY_TYPE_HOUSE",
		3: "PROPERTY_TYPE_OFFICE",
		4: "PROPERTY_TYPE_LAND",
		5: "PROPERTY_TYPE_FARM",
		6: "PROPERTY_TYPE_STUDIO",
		7: "PROPERTY_TYPE_COMMERCIAL",
	}
	PropertyType_value = map[string]int32{
		"PROPERTY_TYPE_UNSPECIFIED": 0,
		"PROPERTY_TYPE_APARTMENT":   1,
		"PROPERTY_TYPE_HOUSE":       2,
		"PROPERTY_TYPE_OFFICE":      3,
		"PROPERTY_TYPE_LAND":        4,
		"PROPERTY_TYPE_FARM":        5,
		"PROPERTY_TYPE_STUDIO":      6,
		"PROPERTY_TYPE_COMMERCIAL":  7,
	}
)

func (x PropertyType) Enum() *PropertyType {
	p := new(PropertyType)
	*p = x
	return p
}

func (x PropertyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PropertyType) Descriptor() protoreflect.EnumDescriptor {
	return file_pikasa_listings_v1_listings_proto_enumTypes[0].Descriptor()
}

func (PropertyType) Type() protoreflect.EnumType {
	return &file_pikasa_listings_v1_listings_proto_enumTypes[0]
}

func (x PropertyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PropertyType.Descriptor instead.
func (PropertyType) EnumDescriptor() ([]byte, []int) {
	return file_pikasa_listings_v1_listings_proto_rawDescGZIP(), []int{0}
}

type TransactionType int32

const (
	TransactionType_TRANSACTION_TYPE_UNSPECIFIED  TransactionType = 0
	TransactionType_TRANSACTION_TYPE_SALE         TransactionType = 1
	TransactionType_TRANSACTION_TYPE_RENT         TransactionType = 2
	TransactionType_TRANSACTION_TYPE_SALE_OR_RENT TransactionType = 3
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "TRANSACTION_TYPE_UNSPECIFIED",
		1: "TRANSACTION_TYPE_SALE",
		2: "TRANSACTION_TYPE_RENT",
		3: "TRANSACTION_TYPE_SALE_OR_RENT",
	}
	TransactionType_value = map[string]int32{
		"TRANSACTION_TYPE_UNSPECIFIED":  0,
		"TRANSACTION_TYPE_SALE":         1,
		"TRANSACTION_TYPE_RENT":         2,
		"TRANSACTION_TYPE_SALE_OR_RENT": 3,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_pikasa_listings_v1_listings_proto_enumTypes[1].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_pikasa_listings_v1_listings_proto_enumTypes[1]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_pikasa_listings_v1_listings_proto_rawDescGZIP(), []int{1}
}

type ListingStatus int32

const (
	ListingStatus_LISTING_STATUS_UNSPECIFIED ListingStatus = 0
	ListingStatus_LISTING_STATUS_ACTIVE      ListingStatus = 1
	ListingStatus_LISTING_STATUS_PAUSED      ListingStatus = 2
	ListingStatus_LISTING_STATUS_REMOVED     ListingStatus = 3
)

// Enum value maps for ListingStatus.
var (
	ListingStatus_name = map[int32]string{
		0: "LISTING_STATUS_UNSPECIFIED",
		1: "LISTING_STATUS_ACTIVE",
		2: "LISTING_STATUS_PAUSED",
		3: "LISTING_STATUS_REMOVED",
	}
	ListingStatus_value = map[string]int32{
		"LISTING_STATUS_UNSPECIFIED": 0,
		"LISTING_STATUS_ACTIVE":      1,
		"LISTING_STATUS_PAUSED":      2,
		"LISTING_STATUS_REMOVED":     3,
	}
)

func (x ListingStatus) Enum() *ListingStatus {
	p := new(ListingStatus)
	*p = x
	return p
}

func (x ListingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pikasa_listings_v1_listings_proto_enumTypes[2].Descriptor()
}

func (ListingStatus) Type() protoreflect.EnumType {
	return &file_pikasa_listings_v1_listings_proto_enumTypes[2]
}

func (x ListingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListingStatus.Descriptor instead.
func (ListingStatus) EnumDescriptor() ([]byte, []int) {
	return file_pikasa_listings_v1_listings_proto_rawDescGZIP(), []int{2}
}

type OrganizationType int32

const (
	OrganizationType_ORGANIZATION_TYPE_UNSPECIFIED OrganizationType = 0
	OrganizationType_ORGANIZATION_TYPE_AGENCY      OrganizationType = 1
	OrganizationType_ORGANIZATION_TYPE_DEVELOPER   OrganizationType = 2
	OrganizationType_ORGANIZATION_TYPE_AGENT       OrganizationType = 3
	OrganizationType_ORGANIZATION_TYPE_OWNER       OrganizationType = 4
)

// Enum value maps for OrganizationType.
var (
	OrganizationType_name = map[int32]string{
		0: "ORGANIZATION_TYPE_UNSPECIFIED",
		1: "ORGANIZATION_TYPE_AGENCY",
		2: "ORGANIZATION_TYPE_DEVELOPER",
		3: "ORGANIZATION_TYPE_AGENT",
		4: "ORGANIZATION_TYPE_OWNER",
	}
	OrganizationType_value = map[string]int32{
		"ORGANIZATION_TYPE_UNSPECIFIED": 0,
		"ORGANIZATION_TYPE_AGENCY":      1,
		"ORGANIZATION_TYPE_DEVELOPER":   2,
		"ORGANIZATION_TYPE_AGENT":       3,
		"ORGANIZATION_TYPE_OWNER":       4,
	}
)

func (x OrganizationType) Enum() *OrganizationType {
	p := new(OrganizationType)
	*p = x
	return p
}

func (x OrganizationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrganizationType) Descriptor() protoreflect.EnumDescriptor {
	return file_pikasa_listings_v1_listings_proto_enumTypes[3].Descriptor()
}

func (OrganizationType) Type() protoreflect.EnumType {
	return &file_pikasa_listings_v1_listings_proto_enumTypes[3]
}

func (x OrganizationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrganizationType.Descriptor instead.
func (OrganizationType) EnumDescriptor() ([]byte, []int) {
	return file_pikasa_listings_v1_listings_proto_rawDescGZIP(), []int{3}
}

type Money struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Minor-unit-free integer amount (COP has no cents in practice; UYU/MXN
	// amounts are whole units). Revisit if a market needs decimals.
	Amount        int64  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"` // ISO 4217, e.g. "COP"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_pikasa_listings_v1_listings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_listings_v1_listings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_pikasa_listings_v1_listings_proto_rawDescGZIP(), []int{0}
}

func (x *Money) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Money) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type RentPrice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Money         *Money                 `protobuf:"bytes,1,opt,name=money,proto3" json:"money,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"` // "monthly" (only value in v1)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RentPrice) Reset() {
	*x = RentPrice{}
	mi := &file_pikasa_listings_v1_listings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RentPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RentPrice) ProtoMessage() {}

func (x *RentPrice) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_listings_v1_listings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RentPrice.ProtoReflect.Descriptor instead.
func (*RentPrice) Descriptor() ([]byte, []int) {
	return file_pikasa_listings_v1_listings_proto_rawDescGZIP(), []int{1}
}

func (x *RentPrice) GetMoney() *Money {
	if x != nil {
		return x.Money
	}
	return nil
}

func (x *RentPrice) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type Price struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sale          *Money                 `protobuf:"bytes,1,opt,name=sale,proto3" json:"sale,omitempty"`
	Rent          *RentPrice             `protobuf:"bytes,2,opt,name=rent,proto3" json:"rent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Price) Reset() {
	*x = Price{}
	mi := &file_pikasa_listings_v1_listings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Price) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Price) ProtoMessage() {}

func (x *Price) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_listings_v1_listings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Price.ProtoReflect.Descriptor instead.
func (*Price) Descriptor() ([]byte, []int) {
	return file_pikasa_listings_v1_listings_proto_rawDescGZIP(), []int{2}
}

func (x *Price) GetSale() *Money {
	if x != nil {
		return x.Sale
	}
	return nil
}

func (x *Price) GetRent() *RentPrice {
	if x != nil {
		return x.Rent
	}
	return nil
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountryCode   string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"` // ISO 3166-1 alpha-2, e.g. "CO"
	Admin1        string                 `protobuf:"bytes,2,opt,name=admin1,proto3" json:"admin1,omitempty"`                              // departamento / provincia / estado
	Admin2        string                 `protobuf:"bytes,3,opt,name=admin2,proto3" json:"admin2,omitempty"`                              // ciudad / municipio
	Neighborhood  string                 `protobuf:"bytes,4,opt,name=neighborhood,proto3" json:"neighborhood,omitempty"`
	Lat           float64                `protobuf:"fixed64,5,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,6,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_pikasa_listings_v1_listings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_listings_v1_listings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_pikasa_listings_v1_listings_proto_rawDescGZIP(), []int{3}
}

func (x *Location) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *Location) GetAdmin1() string {
	if x != nil {
		return x.Admin1
	}
	return ""
}

func (x *Location) GetAdmin2() string {
	if x != nil {
		return x.Admin2
	}
	return ""
}

func (x *Location) GetNeighborhood() string {
	if x != nil {
		return x.Neighborhood
	}
	return ""
}

func (x *Location) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Location) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type Specs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bedrooms      int32                  `protobuf:"varint,1,opt,name=bedrooms,proto3" json:"bedrooms,omitempty"`
	Bathrooms     int32                  `protobuf:"varint,2,opt,name=bathrooms,proto3" json:"bathrooms,omitempty"`
	Parking       int32                  `protobuf:"varint,3,opt,name=parking,proto3" json:"parking,omitempty"`
	AreaBuilt     float64                `protobuf:"fixed64,4,opt,name=area_built,json=areaBuilt,proto3" json:"area_built,omitempty"` // m²
	AreaLot       float64                `protobuf:"fixed64,5,opt,name=area_lot,json=areaLot,proto3" json:"area_lot,omitempty"`       // m²
	YearBuilt     int32                  `protobuf:"varint,6,opt,name=year_built,json=yearBuilt,proto3" json:"year_built,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Specs) Reset() {
	*x = Specs{}
	mi := &file_pikasa_listings_v1_listings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Specs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specs) ProtoMessage() {}

func (x *Specs) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_listings_v1_listings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specs.ProtoReflect.Descriptor instead.
func (*Specs) Descriptor() ([]byte, []int) {
	return file_pikasa_listings_v1_listings_proto_rawDescGZIP(), []int{4}
}

func (x *Specs) GetBedrooms() int32 {
	if x != nil {
		return x.Bedrooms
	}
	return 0
}

func (x *Specs) GetBathrooms() int32 {
	if x != nil {
		return x.Bathrooms
	}
	return 0
}

func (x *Specs) GetParking() int32 {
	if x != nil {
		return x.Parking
	}
	return 0
}

func (x *Specs) GetAreaBuilt() float64 {
	if x != nil {
		return x.AreaBuilt
	}
	return 0
}

func (x *Specs) GetAreaLot() float64 {
	if x != nil {
		return x.AreaLot
	}
	return 0
}

func (x *Specs) GetYearBuilt() int32 {
	if x != nil {
		return x.YearBuilt
	}
	return 0
}

type Photo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Position      int32                  `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Photo) Reset() {
	*x = Photo{}
	mi := &file_pikasa_listings_v1_listings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Photo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Photo) ProtoMessage() {}

func (x *Photo) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_listings_v1_listings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Photo.ProtoReflect.Descriptor instead.
func (*Photo) Descriptor() ([]byte, []int) {
	return file_pikasa_listings_v1_listings_proto_rawDescGZIP(), []int{5}
}

func (x *Photo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Photo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Photo) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type OrganizationCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicId      string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LogoUrl       string                 `protobuf:"bytes,3,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	Type          OrganizationType       `protobuf:"varint,4,opt,name=type,proto3,enum=pikasa.listings.v1.OrganizationType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationCard) Reset() {
	*x = OrganizationCard{}
	mi := &file_pikasa_listings_v1_listings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationCard) ProtoMessage() {}

func (x *OrganizationCard) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_listings_v1_listings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationCard.ProtoReflect.Descriptor instead.
func (*OrganizationCard) Descriptor() ([]byte, []int) {
	return file_pikasa_listings_v1_listings_proto_rawDescGZIP(), []int{6}
}

func (x *OrganizationCard) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *OrganizationCard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrganizationCard) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *OrganizationCard) GetType() OrganizationType {
	if x != nil {
		return x.Type
	}
	return OrganizationType_ORGANIZATION_TYPE_UNSPECIFIED
}

type Listing struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PublicId        string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PropertyType    PropertyType           `protobuf:"varint,4,opt,name=property_type,json=propertyType,proto3,enum=pikasa.listings.v1.PropertyType" json:"property_type,omitempty"`
	TransactionType TransactionType        `protobuf:"varint,5,opt,name=transaction_type,json=transactionType,proto3,enum=pikasa.listings.v1.TransactionType" json:"transaction_type,omitempty"`
	Status          ListingStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=pikasa.listings.v1.ListingStatus" json:"status,omitempty"`
	Price           *Price                 `protobuf:"bytes,7,opt,name=price,proto3" json:"price,omitempty"`
	Location        *Location              `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	Specs           *Specs                 `protobuf:"bytes,9,opt,name=specs,proto3" json:"specs,omitempty"`
	Amenities       []string               `protobuf:"bytes,10,rep,name=amenities,proto3" json:"amenities,omitempty"`
	Photos          []*Photo               `protobuf:"bytes,11,rep,name=photos,proto3" json:"photos,omitempty"`
	CountryFields   map[string]string      `protobuf:"bytes,12,rep,name=country_fields,json=countryFields,proto3" json:"country_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Organization    *OrganizationCard      `protobuf:"bytes,13,opt,name=organization,proto3" json:"organization,omitempty"`
	PublishedAt     string                 `protobuf:"bytes,14,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"` // RFC 3339
	UpdatedAt       string                 `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`       // RFC 3339
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Listing) Reset() {
	*x = Listing{}
	mi := &file_pikasa_listings_v1_listings_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing) ProtoMessage() {}

func (x *Listing) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_listings_v1_listings_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing.ProtoReflect.Descriptor instead.
func (*Listing) Descriptor() ([]byte, []int) {
	return file_pikasa_listings_v1_listings_proto_rawDescGZIP(), []int{7}
}

func (x *Listing) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *Listing) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Listing) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Listing) GetPropertyType() PropertyType {
	if x != nil {
		return x.PropertyType
	}
	return PropertyType_PROPERTY_TYPE_UNSPECIFIED
}

func (x *Listing) GetTransactionType() TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return TransactionType_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *Listing) GetStatus() ListingStatus {
	if x != nil {
		return x.Status
	}
	return ListingStatus_LISTING_STATUS_UNSPECIFIED
}

func (x *Listing) GetPrice() *Price {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Listing) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Listing) GetSpecs() *Specs {
	if x != nil {
		return x.Specs
	}
	return nil
}

func (x *Listing) GetAmenities() []string {
	if x != nil {
		return x.Amenities
	}
	return nil
}

func (x *Listing) GetPhotos() []*Photo {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *Listing) GetCountryFields() map[string]string {
	if x != nil {
		return x.CountryFields
	}
	return nil
}

func (x *Listing) GetOrganization() *OrganizationCard {
	if x != nil {
		return x.Organization
	}
	return nil
}

func (x *Listing) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *Listing) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type SearchListingsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CountryCode     string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Admin2          string                 `protobuf:"bytes,2,opt,name=admin2,proto3" json:"admin2,omitempty"` // optional city filter
	TransactionType TransactionType        `protobuf:"varint,3,opt,name=transaction_type,json=transactionType,proto3,enum=pikasa.listings.v1.TransactionType" json:"transaction_type,omitempty"`
	PropertyType    PropertyType           `protobuf:"varint,4,opt,name=property_type,json=propertyType,proto3,enum=pikasa.listings.v1.PropertyType" json:"property_type,omitempty"`
	MinPrice        int64                  `protobuf:"varint,5,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice        int64                  `protobuf:"varint,6,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	MinBedrooms     int32                  `protobuf:"varint,7,opt,name=min_bedrooms,json=minBedrooms,proto3" json:"min_bedrooms,omitempty"`
	PageSize        int32                  `protobuf:"varint,8,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken       string                 `protobuf:"bytes,9,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // opaque cursor (last listing id)
	// Restrict results to a map viewport. Optional.
	Bbox          *BoundingBox `protobuf:"bytes,10,opt,name=bbox,proto3" json:"bbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchListingsRequest) Reset() {
	*x = SearchListingsRequest{}
	mi := &file_pikasa_listings_v1_listings_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchListingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchListingsRequest) ProtoMessage() {}

func (x *SearchListingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_listings_v1_listings_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchListingsRequest.ProtoReflect.Descriptor instead.
func (*SearchListingsRequest) Descriptor() ([]byte, []int) {
	return file_pikasa_listings_v1_listings_proto_rawDescGZIP(), []int{8}
}

func (x *SearchListingsRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *SearchListingsRequest) GetAdmin2() string {
	if x != nil {
		return x.Admin2
	}
	return ""
}

func (x *SearchListingsRequest) GetTransactionType() TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return TransactionType_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *SearchListingsRequest) GetPropertyType() PropertyType {
	if x != nil {
		return x.PropertyType
	}
	return PropertyType_PROPERTY_TYPE_UNSPECIFIED
}

func (x *SearchListingsRequest) GetMinPrice() int64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *SearchListingsRequest) GetMaxPrice() int64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *SearchListingsRequest) GetMinBedrooms() int32 {
	if x != nil {
		return x.MinBedrooms
	}
	return 0
}

func (x *SearchListingsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchListingsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *SearchListingsRequest) GetBbox() *BoundingBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

type SearchListingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listings      []*Listing             `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchListingsResponse) Reset() {
	*x = SearchListingsResponse{}
	mi := &file_pikasa_listings_v1_listings_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchListingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchListingsResponse) ProtoMessage() {}

func (x *SearchListingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_listings_v1_listings_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchListingsResponse.ProtoReflect.Descriptor instead.
func (*SearchListingsResponse) Descriptor() ([]byte, []int) {
	return file_pikasa_listings_v1_listings_proto_rawDescGZIP(), []int{9}
}

func (x *SearchListingsResponse) GetListings() []*Listing {
	if x != nil {
		return x.Listings
	}
	return nil
}

func (x *SearchListingsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicId      string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingRequest) Reset() {
	*x = GetListingRequest{}
	mi := &file_pikasa_listings_v1_listings_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingRequest) ProtoMessage() {}

func (x *GetListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_listings_v1_listings_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingRequest.ProtoReflect.Descriptor instead.
func (*GetListingRequest) Descriptor() ([]byte, []int) {
	return file_pikasa_listings_v1_listings_proto_rawDescGZIP(), []int{10}
}

func (x *GetListingRequest) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

type GetListingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listing       *Listing               `protobuf:"bytes,1,opt,name=listing,proto3" json:"listing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingResponse) Reset() {
	*x = GetListingResponse{}
	mi := &file_pikasa_listings_v1_listings_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingResponse) ProtoMessage() {}

func (x *GetListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_listings_v1_listings_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingResponse.ProtoReflect.Descriptor instead.
func (*GetListingResponse) Descriptor() ([]byte, []int) {
	return file_pikasa_listings_v1_listings_proto_rawDescGZIP(), []int{11}
}

func (x *GetListingResponse) GetListing() *Listing {
	if x != nil {
		return x.Listing
	}
	return nil
}

type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinLon        float64                `protobuf:"fixed64,1,opt,name=min_lon,json=minLon,proto3" json:"min_lon,omitempty"`
	MinLat        float64                `protobuf:"fixed64,2,opt,name=min_lat,json=minLat,proto3" json:"min_lat,omitempty"`
	MaxLon        float64                `protobuf:"fixed64,3,opt,name=max_lon,json=maxLon,proto3" json:"max_lon,omitempty"`
	MaxLat        float64                `protobuf:"fixed64,4,opt,name=max_lat,json=maxLat,proto3" json:"max_lat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_pikasa_listings_v1_listings_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_listings_v1_listings_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_pikasa_listings_v1_listings_proto_rawDescGZIP(), []int{12}
}

func (x *BoundingBox) GetMinLon() float64 {
	if x != nil {
		return x.MinLon
	}
	return 0
}

func (x *BoundingBox) GetMinLat() float64 {
	if x != nil {
		return x.MinLat
	}
	return 0
}

func (x *BoundingBox) GetMaxLon() float64 {
	if x != nil {
		return x.MaxLon
	}
	return 0
}

func (x *BoundingBox) GetMaxLat() float64 {
	if x != nil {
		return x.MaxLat
	}
	return 0
}

var File_pikasa_listings_v1_listings_proto protoreflect.FileDescriptor

const file_pikasa_listings_v1_listings_proto_rawDesc = "" +
	"\n" +
	"!pikasa/listings/v1/listings.proto\x12\x12pikasa.listings.v1\x1a\x1bbuf/validate/validate.proto\";\n" +
	"\x05Money\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"T\n" +
	"\tRentPrice\x12/\n" +
	"\x05money\x18\x01 \x01(\v2\x19.pikasa.listings.v1.MoneyR\x05money\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\"i\n" +
	"\x05Price\x12-\n" +
	"\x04sale\x18\x01 \x01(\v2\x19.pikasa.listings.v1.MoneyR\x04sale\x121\n" +
	"\x04rent\x18\x02 \x01(\v2\x1d.pikasa.listings.v1.RentPriceR\x04rent\"\xa5\x01\n" +
	"\bLocation\x12!\n" +
	"\fcountry_code\x18\x01 \x01(\tR\vcountryCode\x12\x16\n" +
	"\x06admin1\x18\x02 \x01(\tR\x06admin1\x12\x16\n" +
	"\x06admin2\x18\x03 \x01(\tR\x06admin2\x12\"\n" +
	"\fneighborhood\x18\x04 \x01(\tR\fneighborhood\x12\x10\n" +
	"\x03lat\x18\x05 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x06 \x01(\x01R\x03lon\"\xb4\x01\n" +
	"\x05Specs\x12\x1a\n" +
	"\bbedrooms\x18\x01 \x01(\x05R\bbedrooms\x12\x1c\n" +
	"\tbathrooms\x18\x02 \x01(\x05R\tbathrooms\x12\x18\n" +
	"\aparking\x18\x03 \x01(\x05R\aparking\x12\x1d\n" +
	"\n" +
	"area_built\x18\x04 \x01(\x01R\tareaBuilt\x12\x19\n" +
	"\barea_lot\x18\x05 \x01(\x01R\aareaLot\x12\x1d\n" +
	"\n" +
	"year_built\x18\x06 \x01(\x05R\tyearBuilt\"E\n" +
	"\x05Photo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x05R\bposition\"\x98\x01\n" +
	"\x10OrganizationCard\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\blogo_url\x18\x03 \x01(\tR\alogoUrl\x128\n" +
	"\x04type\x18\x04 \x01(\x0e2$.pikasa.listings.v1.OrganizationTypeR\x04type\"\xc2\x06\n" +
	"\aListing\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12E\n" +
	"\rproperty_type\x18\x04 \x01(\x0e2 .pikasa.listings.v1.PropertyTypeR\fpropertyType\x12N\n" +
	"\x10transaction_type\x18\x05 \x01(\x0e2#.pikasa.listings.v1.TransactionTypeR\x0ftransactionType\x129\n" +
	"\x06status\x18\x06 \x01(\x0e2!.pikasa.listings.v1.ListingStatusR\x06status\x12/\n" +
	"\x05price\x18\a \x01(\v2\x19.pikasa.listings.v1.PriceR\x05price\x128\n" +
	"\blocation\x18\b \x01(\v2\x1c.pikasa.listings.v1.LocationR\blocation\x12/\n" +
	"\x05specs\x18\t \x01(\v2\x19.pikasa.listings.v1.SpecsR\x05specs\x12\x1c\n" +
	"\tamenities\x18\n" +
	" \x03(\tR\tamenities\x121\n" +
	"\x06photos\x18\v \x03(\v2\x19.pikasa.listings.v1.PhotoR\x06photos\x12U\n" +
	"\x0ecountry_fields\x18\f \x03(\v2..pikasa.listings.v1.Listing.CountryFieldsEntryR\rcountryFields\x12H\n" +
	"\forganization\x18\r \x01(\v2$.pikasa.listings.v1.OrganizationCardR\forganization\x12!\n" +
	"\fpublished_at\x18\x0e \x01(\tR\vpublishedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\tR\tupdatedAt\x1a@\n" +
	"\x12CountryFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcc\x03\n" +
	"\x15SearchListingsRequest\x12+\n" +
	"\fcountry_code\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x02R\vcountryCode\x12\x16\n" +
	"\x06admin2\x18\x02 \x01(\tR\x06admin2\x12N\n" +
	"\x10transaction_type\x18\x03 \x01(\x0e2#.pikasa.listings.v1.TransactionTypeR\x0ftransactionType\x12E\n" +
	"\rproperty_type\x18\x04 \x01(\x0e2 .pikasa.listings.v1.PropertyTypeR\fpropertyType\x12\x1b\n" +
	"\tmin_price\x18\x05 \x01(\x03R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x06 \x01(\x03R\bmaxPrice\x12!\n" +
	"\fmin_bedrooms\x18\a \x01(\x05R\vminBedrooms\x12&\n" +
	"\tpage_size\x18\b \x01(\x05B\t\xbaH\x06\x1a\x04\x182(\x00R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\t \x01(\tR\tpageToken\x123\n" +
	"\x04bbox\x18\n" +
	" \x01(\v2\x1f.pikasa.listings.v1.BoundingBoxR\x04bbox\"y\n" +
	"\x16SearchListingsResponse\x127\n" +
	"\blistings\x18\x01 \x03(\v2\x1b.pikasa.listings.v1.ListingR\blistings\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"9\n" +
	"\x11GetListingRequest\x12$\n" +
	"\tpublic_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bpublicId\"K\n" +
	"\x12GetListingResponse\x125\n" +
	"\alisting\x18\x01 \x01(\v2\x1b.pikasa.listings.v1.ListingR\alisting\"\xd5\x01\n" +
	"\vBoundingBox\x120\n" +
	"\amin_lon\x18\x01 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80f@)\x00\x00\x00\x00\x00\x80f\xc0R\x06minLon\x120\n" +
	"\amin_lat\x18\x02 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80V@)\x00\x00\x00\x00\x00\x80V\xc0R\x06minLat\x120\n" +
	"\amax_lon\x18\x03 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80f@)\x00\x00\x00\x00\x00\x80f\xc0R\x06maxLon\x120\n" +
	"\amax_lat\x18\x04 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80V@)\x00\x00\x00\x00\x00\x80V\xc0R\x06maxLat*\xe5\x01\n" +
	"\fPropertyType\x12\x1d\n" +
	"\x19PROPERTY_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PROPERTY_TYPE_APARTMENT\x10\x01\x12\x17\n" +
	"\x13PROPERTY_TYPE_HOUSE\x10\x02\x12\x18\n" +
	"\x14PROPERTY_TYPE_OFFICE\x10\x03\x12\x16\n" +
	"\x12PROPERTY_TYPE_LAND\x10\x04\x12\x16\n" +
	"\x12PROPERTY_TYPE_FARM\x10\x05\x12\x18\n" +
	"\x14PROPERTY_TYPE_STUDIO\x10\x06\x12\x1c\n" +
	"\x18PROPERTY_TYPE_COMMERCIAL\x10\a*\x8c\x01\n" +
	"\x0fTransactionType\x12 \n" +
	"\x1cTRANSACTION_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TRANSACTION_TYPE_SALE\x10\x01\x12\x19\n" +
	"\x15TRANSACTION_TYPE_RENT\x10\x02\x12!\n" +
	"\x1dTRANSACTION_TYPE_SALE_OR_RENT\x10\x03*\x81\x01\n" +
	"\rListingStatus\x12\x1e\n" +
	"\x1aLISTING_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15LISTING_STATUS_ACTIVE\x10\x01\x12\x19\n" +
	"\x15LISTING_STATUS_PAUSED\x10\x02\x12\x1a\n" +
	"\x16LISTING_STATUS_REMOVED\x10\x03*\xae\x01\n" +
	"\x10OrganizationType\x12!\n" +
	"\x1dORGANIZATION_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ORGANIZATION_TYPE_AGENCY\x10\x01\x12\x1f\n" +
	"\x1bORGANIZATION_TYPE_DEVELOPER\x10\x02\x12\x1b\n" +
	"\x17ORGANIZATION_TYPE_AGENT\x10\x03\x12\x1b\n" +
	"\x17ORGANIZATION_TYPE_OWNER\x10\x042\xd7\x01\n" +
	"\x0fListingsService\x12g\n" +
	"\x0eSearchListings\x12).pikasa.listings.v1.SearchListingsRequest\x1a*.pikasa.listings.v1.SearchListingsResponse\x12[\n" +
	"\n" +
	"GetListing\x12%.pikasa.listings.v1.GetListingRequest\x1a&.pikasa.listings.v1.GetListingResponseB\xce\x01\n" +
	"\x16com.pikasa.listings.v1B\rListingsProtoP\x01Z;github.com/pikasaco/pikasa-go/pikasa/listings/v1;listingsv1\xa2\x02\x03PLX\xaa\x02\x12Pikasa.Listings.V1\xca\x02\x12Pikasa\\Listings\\V1\xe2\x02\x1ePikasa\\Listings\\V1\\GPBMetadata\xea\x02\x14Pikasa::Listings::V1b\x06proto3"

var (
	file_pikasa_listings_v1_listings_proto_rawDescOnce sync.Once
	file_pikasa_listings_v1_listings_proto_rawDescData []byte
)

func file_pikasa_listings_v1_listings_proto_rawDescGZIP() []byte {
	file_pikasa_listings_v1_listings_proto_rawDescOnce.Do(func() {
		file_pikasa_listings_v1_listings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pikasa_listings_v1_listings_proto_rawDesc), len(file_pikasa_listings_v1_listings_proto_rawDesc)))
	})
	return file_pikasa_listings_v1_listings_proto_rawDescData
}

var file_pikasa_listings_v1_listings_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_pikasa_listings_v1_listings_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pikasa_listings_v1_listings_proto_goTypes = []any{
	(PropertyType)(0),              // 0: pikasa.listings.v1.PropertyType
	(TransactionType)(0),           // 1: pikasa.listings.v1.TransactionType
	(ListingStatus)(0),             // 2: pikasa.listings.v1.ListingStatus
	(OrganizationType)(0),          // 3: pikasa.listings.v1.OrganizationType
	(*Money)(nil),                  // 4: pikasa.listings.v1.Money
	(*RentPrice)(nil),              // 5: pikasa.listings.v1.RentPrice
	(*Price)(nil),                  // 6: pikasa.listings.v1.Price
	(*Location)(nil),               // 7: pikasa.listings.v1.Location
	(*Specs)(nil),                  // 8: pikasa.listings.v1.Specs
	(*Photo)(nil),                  // 9: pikasa.listings.v1.Photo
	(*OrganizationCard)(nil),       // 10: pikasa.listings.v1.OrganizationCard
	(*Listing)(nil),                // 11: pikasa.listings.v1.Listing
	(*SearchListingsRequest)(nil),  // 12: pikasa.listings.v1.SearchListingsRequest
	(*SearchListingsResponse)(nil), // 13: pikasa.listings.v1.SearchListingsResponse
	(*GetListingRequest)(nil),      // 14: pikasa.listings.v1.GetListingRequest
	(*GetListingResponse)(nil),     // 15: pikasa.listings.v1.GetListingResponse
	(*BoundingBox)(nil),            // 16: pikasa.listings.v1.BoundingBox
	nil,                            // 17: pikasa.listings.v1.Listing.CountryFieldsEntry
}
var file_pikasa_listings_v1_listings_proto_depIdxs = []int32{
	4,  // 0: pikasa.listings.v1.RentPrice.money:type_name -> pikasa.listings.v1.Money
	4,  // 1: pikasa.listings.v1.Price.sale:type_name -> pikasa.listings.v1.Money
	5,  // 2: pikasa.listings.v1.Price.rent:type_name -> pikasa.listings.v1.RentPrice
	3,  // 3: pikasa.listings.v1.OrganizationCard.type:type_name -> pikasa.listings.v1.OrganizationType
	0,  // 4: pikasa.listings.v1.Listing.property_type:type_name -> pikasa.listings.v1.PropertyType
	1,  // 5: pikasa.listings.v1.Listing.transaction_type:type_name -> pikasa.listings.v1.TransactionType
	2,  // 6: pikasa.listings.v1.Listing.status:type_name -> pikasa.listings.v1.ListingStatus
	6,  // 7: pikasa.listings.v1.Listing.price:type_name -> pikasa.listings.v1.Price
	7,  // 8: pikasa.listings.v1.Listing.location:type_name -> pikasa.listings.v1.Location
	8,  // 9: pikasa.listings.v1.Listing.specs:type_name -> pikasa.listings.v1.Specs
	9,  // 10: pikasa.listings.v1.Listing.photos:type_name -> pikasa.listings.v1.Photo
	17, // 11: pikasa.listings.v1.Listing.country_fields:type_name -> pikasa.listings.v1.Listing.CountryFieldsEntry
	10, // 12: pikasa.listings.v1.Listing.organization:type_name -> pikasa.listings.v1.OrganizationCard
	1,  // 13: pikasa.listings.v1.SearchListingsRequest.transaction_type:type_name -> pikasa.listings.v1.TransactionType
	0,  // 14: pikasa.listings.v1.SearchListingsRequest.property_type:type_name -> pikasa.listings.v1.PropertyType
	16, // 15: pikasa.listings.v1.SearchListingsRequest.bbox:type_name -> pikasa.listings.v1.BoundingBox
	11, // 16: pikasa.listings.v1.SearchListingsResponse.listings:type_name -> pikasa.listings.v1.Listing
	11, // 17: pikasa.listings.v1.GetListingResponse.listing:type_name -> pikasa.listings.v1.Listing
	12, // 18: pikasa.listings.v1.ListingsService.SearchListings:input_type -> pikasa.listings.v1.SearchListingsRequest
	14, // 19: pikasa.listings.v1.ListingsService.GetListing:input_type -> pikasa.listings.v1.GetListingRequest
	13, // 20: pikasa.listings.v1.ListingsService.SearchListings:output_type -> pikasa.listings.v1.SearchListingsResponse
	15, // 21: pikasa.listings.v1.ListingsService.GetListing:output_type -> pikasa.listings.v1.GetListingResponse
	20, // [20:22] is the sub-list for method output_type
	18, // [18:20] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_pikasa_listings_v1_listings_proto_init() }
func file_pikasa_listings_v1_listings_proto_init() {
	if File_pikasa_listings_v1_listings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pikasa_listings_v1_listings_proto_rawDesc), len(file_pikasa_listings_v1_listings_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pikasa_listings_v1_listings_proto_goTypes,
		DependencyIndexes: file_pikasa_listings_v1_listings_proto_depIdxs,
		EnumInfos:         file_pikasa_listings_v1_listings_proto_enumTypes,
		MessageInfos:      file_pikasa_listings_v1_listings_proto_msgTypes,
	}.Build()
	File_pikasa_listings_v1_listings_proto = out.File
	file_pikasa_listings_v1_listings_proto_goTypes = nil
	file_pikasa_listings_v1_listings_proto_depIdxs = nil
}
