// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pikasa/integrators/v1/integrators.proto

package integratorsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/pikasaco/pikasa-go/pikasa/integrators/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// IntegratorServiceName is the fully-qualified name of the IntegratorService service.
	IntegratorServiceName = "pikasa.integrators.v1.IntegratorService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IntegratorServiceUpsertOrganizationProcedure is the fully-qualified name of the
	// IntegratorService's UpsertOrganization RPC.
	IntegratorServiceUpsertOrganizationProcedure = "/pikasa.integrators.v1.IntegratorService/UpsertOrganization"
	// IntegratorServiceUpsertListingProcedure is the fully-qualified name of the IntegratorService's
	// UpsertListing RPC.
	IntegratorServiceUpsertListingProcedure = "/pikasa.integrators.v1.IntegratorService/UpsertListing"
	// IntegratorServiceRemoveListingProcedure is the fully-qualified name of the IntegratorService's
	// RemoveListing RPC.
	IntegratorServiceRemoveListingProcedure = "/pikasa.integrators.v1.IntegratorService/RemoveListing"
	// IntegratorServiceSetWebhookProcedure is the fully-qualified name of the IntegratorService's
	// SetWebhook RPC.
	IntegratorServiceSetWebhookProcedure = "/pikasa.integrators.v1.IntegratorService/SetWebhook"
)

// IntegratorServiceClient is a client for the pikasa.integrators.v1.IntegratorService service.
type IntegratorServiceClient interface {
	UpsertOrganization(context.Context, *connect.Request[v1.UpsertOrganizationRequest]) (*connect.Response[v1.UpsertOrganizationResponse], error)
	UpsertListing(context.Context, *connect.Request[v1.UpsertListingRequest]) (*connect.Response[v1.UpsertListingResponse], error)
	RemoveListing(context.Context, *connect.Request[v1.RemoveListingRequest]) (*connect.Response[v1.RemoveListingResponse], error)
	SetWebhook(context.Context, *connect.Request[v1.SetWebhookRequest]) (*connect.Response[v1.SetWebhookResponse], error)
}

// NewIntegratorServiceClient constructs a client for the pikasa.integrators.v1.IntegratorService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIntegratorServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IntegratorServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	integratorServiceMethods := v1.File_pikasa_integrators_v1_integrators_proto.Services().ByName("IntegratorService").Methods()
	return &integratorServiceClient{
		upsertOrganization: connect.NewClient[v1.UpsertOrganizationRequest, v1.UpsertOrganizationResponse](
			httpClient,
			baseURL+IntegratorServiceUpsertOrganizationProcedure,
			connect.WithSchema(integratorServiceMethods.ByName("UpsertOrganization")),
			connect.WithClientOptions(opts...),
		),
		upsertListing: connect.NewClient[v1.UpsertListingRequest, v1.UpsertListingResponse](
			httpClient,
			baseURL+IntegratorServiceUpsertListingProcedure,
			connect.WithSchema(integratorServiceMethods.ByName("UpsertListing")),
			connect.WithClientOptions(opts...),
		),
		removeListing: connect.NewClient[v1.RemoveListingRequest, v1.RemoveListingResponse](
			httpClient,
			baseURL+IntegratorServiceRemoveListingProcedure,
			connect.WithSchema(integratorServiceMethods.ByName("RemoveListing")),
			connect.WithClientOptions(opts...),
		),
		setWebhook: connect.NewClient[v1.SetWebhookRequest, v1.SetWebhookResponse](
			httpClient,
			baseURL+IntegratorServiceSetWebhookProcedure,
			connect.WithSchema(integratorServiceMethods.ByName("SetWebhook")),
			connect.WithClientOptions(opts...),
		),
	}
}

// integratorServiceClient implements IntegratorServiceClient.
type integratorServiceClient struct {
	upsertOrganization *connect.Client[v1.UpsertOrganizationRequest, v1.UpsertOrganizationResponse]
	upsertListing      *connect.Client[v1.UpsertListingRequest, v1.UpsertListingResponse]
	removeListing      *connect.Client[v1.RemoveListingRequest, v1.RemoveListingResponse]
	setWebhook         *connect.Client[v1.SetWebhookRequest, v1.SetWebhookResponse]
}

// UpsertOrganization calls pikasa.integrators.v1.IntegratorService.UpsertOrganization.
func (c *integratorServiceClient) UpsertOrganization(ctx context.Context, req *connect.Request[v1.UpsertOrganizationRequest]) (*connect.Response[v1.UpsertOrganizationResponse], error) {
	return c.upsertOrganization.CallUnary(ctx, req)
}

// UpsertListing calls pikasa.integrators.v1.IntegratorService.UpsertListing.
func (c *integratorServiceClient) UpsertListing(ctx context.Context, req *connect.Request[v1.UpsertListingRequest]) (*connect.Response[v1.UpsertListingResponse], error) {
	return c.upsertListing.CallUnary(ctx, req)
}

// RemoveListing calls pikasa.integrators.v1.IntegratorService.RemoveListing.
func (c *integratorServiceClient) RemoveListing(ctx context.Context, req *connect.Request[v1.RemoveListingRequest]) (*connect.Response[v1.RemoveListingResponse], error) {
	return c.removeListing.CallUnary(ctx, req)
}

// SetWebhook calls pikasa.integrators.v1.IntegratorService.SetWebhook.
func (c *integratorServiceClient) SetWebhook(ctx context.Context, req *connect.Request[v1.SetWebhookRequest]) (*connect.Response[v1.SetWebhookResponse], error) {
	return c.setWebhook.CallUnary(ctx, req)
}

// IntegratorServiceHandler is an implementation of the pikasa.integrators.v1.IntegratorService
// service.
type IntegratorServiceHandler interface {
	UpsertOrganization(context.Context, *connect.Request[v1.UpsertOrganizationRequest]) (*connect.Response[v1.UpsertOrganizationResponse], error)
	UpsertListing(context.Context, *connect.Request[v1.UpsertListingRequest]) (*connect.Response[v1.UpsertListingResponse], error)
	RemoveListing(context.Context, *connect.Request[v1.RemoveListingRequest]) (*connect.Response[v1.RemoveListingResponse], error)
	SetWebhook(context.Context, *connect.Request[v1.SetWebhookRequest]) (*connect.Response[v1.SetWebhookResponse], error)
}

// NewIntegratorServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIntegratorServiceHandler(svc IntegratorServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	integratorServiceMethods := v1.File_pikasa_integrators_v1_integrators_proto.Services().ByName("IntegratorService").Methods()
	integratorServiceUpsertOrganizationHandler := connect.NewUnaryHandler(
		IntegratorServiceUpsertOrganizationProcedure,
		svc.UpsertOrganization,
		connect.WithSchema(integratorServiceMethods.ByName("UpsertOrganization")),
		connect.WithHandlerOptions(opts...),
	)
	integratorServiceUpsertListingHandler := connect.NewUnaryHandler(
		IntegratorServiceUpsertListingProcedure,
		svc.UpsertListing,
		connect.WithSchema(integratorServiceMethods.ByName("UpsertListing")),
		connect.WithHandlerOptions(opts...),
	)
	integratorServiceRemoveListingHandler := connect.NewUnaryHandler(
		IntegratorServiceRemoveListingProcedure,
		svc.RemoveListing,
		connect.WithSchema(integratorServiceMethods.ByName("RemoveListing")),
		connect.WithHandlerOptions(opts...),
	)
	integratorServiceSetWebhookHandler := connect.NewUnaryHandler(
		IntegratorServiceSetWebhookProcedure,
		svc.SetWebhook,
		connect.WithSchema(integratorServiceMethods.ByName("SetWebhook")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pikasa.integrators.v1.IntegratorService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case IntegratorServiceUpsertOrganizationProcedure:
			integratorServiceUpsertOrganizationHandler.ServeHTTP(w, r)
		case IntegratorServiceUpsertListingProcedure:
			integratorServiceUpsertListingHandler.ServeHTTP(w, r)
		case IntegratorServiceRemoveListingProcedure:
			integratorServiceRemoveListingHandler.ServeHTTP(w, r)
		case IntegratorServiceSetWebhookProcedure:
			integratorServiceSetWebhookHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedIntegratorServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedIntegratorServiceHandler struct{}

func (UnimplementedIntegratorServiceHandler) UpsertOrganization(context.Context, *connect.Request[v1.UpsertOrganizationRequest]) (*connect.Response[v1.UpsertOrganizationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pikasa.integrators.v1.IntegratorService.UpsertOrganization is not implemented"))
}

func (UnimplementedIntegratorServiceHandler) UpsertListing(context.Context, *connect.Request[v1.UpsertListingRequest]) (*connect.Response[v1.UpsertListingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pikasa.integrators.v1.IntegratorService.UpsertListing is not implemented"))
}

func (UnimplementedIntegratorServiceHandler) RemoveListing(context.Context, *connect.Request[v1.RemoveListingRequest]) (*connect.Response[v1.RemoveListingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pikasa.integrators.v1.IntegratorService.RemoveListing is not implemented"))
}

func (UnimplementedIntegratorServiceHandler) SetWebhook(context.Context, *connect.Request[v1.SetWebhookRequest]) (*connect.Response[v1.SetWebhookResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pikasa.integrators.v1.IntegratorService.SetWebhook is not implemented"))
}
