// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pikasa/leads/v1/leads.proto

package leadsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/pikasaco/pikasa-go/pikasa/leads/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LeadsServiceName is the fully-qualified name of the LeadsService service.
	LeadsServiceName = "pikasa.leads.v1.LeadsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LeadsServiceCreateLeadProcedure is the fully-qualified name of the LeadsService's CreateLead RPC.
	LeadsServiceCreateLeadProcedure = "/pikasa.leads.v1.LeadsService/CreateLead"
)

// LeadsServiceClient is a client for the pikasa.leads.v1.LeadsService service.
type LeadsServiceClient interface {
	CreateLead(context.Context, *connect.Request[v1.CreateLeadRequest]) (*connect.Response[v1.CreateLeadResponse], error)
}

// NewLeadsServiceClient constructs a client for the pikasa.leads.v1.LeadsService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLeadsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LeadsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	leadsServiceMethods := v1.File_pikasa_leads_v1_leads_proto.Services().ByName("LeadsService").Methods()
	return &leadsServiceClient{
		createLead: connect.NewClient[v1.CreateLeadRequest, v1.CreateLeadResponse](
			httpClient,
			baseURL+LeadsServiceCreateLeadProcedure,
			connect.WithSchema(leadsServiceMethods.ByName("CreateLead")),
			connect.WithClientOptions(opts...),
		),
	}
}

// leadsServiceClient implements LeadsServiceClient.
type leadsServiceClient struct {
	createLead *connect.Client[v1.CreateLeadRequest, v1.CreateLeadResponse]
}

// CreateLead calls pikasa.leads.v1.LeadsService.CreateLead.
func (c *leadsServiceClient) CreateLead(ctx context.Context, req *connect.Request[v1.CreateLeadRequest]) (*connect.Response[v1.CreateLeadResponse], error) {
	return c.createLead.CallUnary(ctx, req)
}

// LeadsServiceHandler is an implementation of the pikasa.leads.v1.LeadsService service.
type LeadsServiceHandler interface {
	CreateLead(context.Context, *connect.Request[v1.CreateLeadRequest]) (*connect.Response[v1.CreateLeadResponse], error)
}

// NewLeadsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLeadsServiceHandler(svc LeadsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	leadsServiceMethods := v1.File_pikasa_leads_v1_leads_proto.Services().ByName("LeadsService").Methods()
	leadsServiceCreateLeadHandler := connect.NewUnaryHandler(
		LeadsServiceCreateLeadProcedure,
		svc.CreateLead,
		connect.WithSchema(leadsServiceMethods.ByName("CreateLead")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pikasa.leads.v1.LeadsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LeadsServiceCreateLeadProcedure:
			leadsServiceCreateLeadHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLeadsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLeadsServiceHandler struct{}

func (UnimplementedLeadsServiceHandler) CreateLead(context.Context, *connect.Request[v1.CreateLeadRequest]) (*connect.Response[v1.CreateLeadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pikasa.leads.v1.LeadsService.CreateLead is not implemented"))
}
