// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pikasa/discovery/v1/discovery.proto

package discoveryv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/pikasaco/pikasa-go/pikasa/listings/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiscoverRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	CountryCode string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	// City, matched ignoring case and accents ("medellin" finds "Medellín").
	Admin2 string `protobuf:"bytes,2,opt,name=admin2,proto3" json:"admin2,omitempty"`
	// Neighbourhood, matched the same way. Naming varies between sources, so
	// prefer admin2 or bbox when completeness matters.
	Neighborhood string `protobuf:"bytes,3,opt,name=neighborhood,proto3" json:"neighborhood,omitempty"`
	// UNSPECIFIED and SALE_OR_RENT both mean either.
	TransactionType v1.TransactionType `protobuf:"varint,4,opt,name=transaction_type,json=transactionType,proto3,enum=pikasa.listings.v1.TransactionType" json:"transaction_type,omitempty"`
	// Match any of these types, e.g. [HOUSE, APARTMENT]. Empty = any type.
	PropertyTypes []v1.PropertyType `protobuf:"varint,5,rep,packed,name=property_types,json=propertyTypes,proto3,enum=pikasa.listings.v1.PropertyType" json:"property_types,omitempty"`
	// Price bounds apply to the price of the chosen transaction type, so they
	// require transaction_type SALE or RENT: a sale price and a monthly rent
	// are not on one scale.
	MinPrice    int64           `protobuf:"varint,6,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice    int64           `protobuf:"varint,7,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	MinBedrooms int32           `protobuf:"varint,8,opt,name=min_bedrooms,json=minBedrooms,proto3" json:"min_bedrooms,omitempty"`
	Bbox        *v1.BoundingBox `protobuf:"bytes,9,opt,name=bbox,proto3" json:"bbox,omitempty"`
	// New-build projects advertise a price range rather than a unit; excluded
	// unless asked for.
	IncludeDevelopments bool   `protobuf:"varint,10,opt,name=include_developments,json=includeDevelopments,proto3" json:"include_developments,omitempty"`
	PageSize            int32  `protobuf:"varint,11,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken           string `protobuf:"bytes,12,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // opaque cursor
	// Restrict results to a radius around a point, nearest first, each with its
	// distance_m. Not combinable with bbox. Without it, results are ordered
	// most recently verified first.
	Near          *v1.Near `protobuf:"bytes,13,opt,name=near,proto3" json:"near,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_pikasa_discovery_v1_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_discovery_v1_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_pikasa_discovery_v1_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *DiscoverRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *DiscoverRequest) GetAdmin2() string {
	if x != nil {
		return x.Admin2
	}
	return ""
}

func (x *DiscoverRequest) GetNeighborhood() string {
	if x != nil {
		return x.Neighborhood
	}
	return ""
}

func (x *DiscoverRequest) GetTransactionType() v1.TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return v1.TransactionType(0)
}

func (x *DiscoverRequest) GetPropertyTypes() []v1.PropertyType {
	if x != nil {
		return x.PropertyTypes
	}
	return nil
}

func (x *DiscoverRequest) GetMinPrice() int64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *DiscoverRequest) GetMaxPrice() int64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *DiscoverRequest) GetMinBedrooms() int32 {
	if x != nil {
		return x.MinBedrooms
	}
	return 0
}

func (x *DiscoverRequest) GetBbox() *v1.BoundingBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *DiscoverRequest) GetIncludeDevelopments() bool {
	if x != nil {
		return x.IncludeDevelopments
	}
	return false
}

func (x *DiscoverRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *DiscoverRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *DiscoverRequest) GetNear() *v1.Near {
	if x != nil {
		return x.Near
	}
	return nil
}

type DiscoverResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Most recently verified first; nearest first when the request has near.
	Results       []*Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	NextPageToken string    `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverResponse) Reset() {
	*x = DiscoverResponse{}
	mi := &file_pikasa_discovery_v1_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResponse) ProtoMessage() {}

func (x *DiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_discovery_v1_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResponse.ProtoReflect.Descriptor instead.
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return file_pikasa_discovery_v1_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *DiscoverResponse) GetResults() []*Result {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *DiscoverResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type Result struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Where the property is published. Always set.
	Source       *Source         `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Title        string          `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	PropertyType v1.PropertyType `protobuf:"varint,3,opt,name=property_type,json=propertyType,proto3,enum=pikasa.listings.v1.PropertyType" json:"property_type,omitempty"`
	SalePrice    *v1.Money       `protobuf:"bytes,4,opt,name=sale_price,json=salePrice,proto3" json:"sale_price,omitempty"` // unset when not for sale
	RentPrice    *v1.Money       `protobuf:"bytes,5,opt,name=rent_price,json=rentPrice,proto3" json:"rent_price,omitempty"` // unset when not for rent; monthly
	// Location.lat/lon mean nothing unless has_location is set.
	Location    *v1.Location `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	HasLocation bool         `protobuf:"varint,7,opt,name=has_location,json=hasLocation,proto3" json:"has_location,omitempty"`
	AreaM2      float64      `protobuf:"fixed64,8,opt,name=area_m2,json=areaM2,proto3" json:"area_m2,omitempty"`
	Bedrooms    int32        `protobuf:"varint,9,opt,name=bedrooms,proto3" json:"bedrooms,omitempty"`
	Bathrooms   int32        `protobuf:"varint,10,opt,name=bathrooms,proto3" json:"bathrooms,omitempty"`
	// Hosted at the source.
	PhotoUrls     []string `protobuf:"bytes,11,rep,name=photo_urls,json=photoUrls,proto3" json:"photo_urls,omitempty"`
	IsDevelopment bool     `protobuf:"varint,12,opt,name=is_development,json=isDevelopment,proto3" json:"is_development,omitempty"`
	// Metres from the request's near point; set only when it had one.
	DistanceM     *float64 `protobuf:"fixed64,13,opt,name=distance_m,json=distanceM,proto3,oneof" json:"distance_m,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_pikasa_discovery_v1_discovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_discovery_v1_discovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_pikasa_discovery_v1_discovery_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetSource() *Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Result) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Result) GetPropertyType() v1.PropertyType {
	if x != nil {
		return x.PropertyType
	}
	return v1.PropertyType(0)
}

func (x *Result) GetSalePrice() *v1.Money {
	if x != nil {
		return x.SalePrice
	}
	return nil
}

func (x *Result) GetRentPrice() *v1.Money {
	if x != nil {
		return x.RentPrice
	}
	return nil
}

func (x *Result) GetLocation() *v1.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Result) GetHasLocation() bool {
	if x != nil {
		return x.HasLocation
	}
	return false
}

func (x *Result) GetAreaM2() float64 {
	if x != nil {
		return x.AreaM2
	}
	return 0
}

func (x *Result) GetBedrooms() int32 {
	if x != nil {
		return x.Bedrooms
	}
	return 0
}

func (x *Result) GetBathrooms() int32 {
	if x != nil {
		return x.Bathrooms
	}
	return 0
}

func (x *Result) GetPhotoUrls() []string {
	if x != nil {
		return x.PhotoUrls
	}
	return nil
}

func (x *Result) GetIsDevelopment() bool {
	if x != nil {
		return x.IsDevelopment
	}
	return false
}

func (x *Result) GetDistanceM() float64 {
	if x != nil && x.DistanceM != nil {
		return *x.DistanceM
	}
	return 0
}

type Source struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Url                  string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`                                             // the property's page at its source
	Host                 string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`                                           // e.g. "www.example.com", for attribution
	AdvertiserName       string                 `protobuf:"bytes,3,opt,name=advertiser_name,json=advertiserName,proto3" json:"advertiser_name,omitempty"` // as the source shows it; may be empty
	AdvertiserProfileUrl string                 `protobuf:"bytes,4,opt,name=advertiser_profile_url,json=advertiserProfileUrl,proto3" json:"advertiser_profile_url,omitempty"`
	IndexedAt            string                 `protobuf:"bytes,5,opt,name=indexed_at,json=indexedAt,proto3" json:"indexed_at,omitempty"`    // RFC 3339 — when discovery first found it
	VerifiedAt           string                 `protobuf:"bytes,6,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"` // RFC 3339 — when it was last confirmed live
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_pikasa_discovery_v1_discovery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_discovery_v1_discovery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_pikasa_discovery_v1_discovery_proto_rawDescGZIP(), []int{3}
}

func (x *Source) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Source) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Source) GetAdvertiserName() string {
	if x != nil {
		return x.AdvertiserName
	}
	return ""
}

func (x *Source) GetAdvertiserProfileUrl() string {
	if x != nil {
		return x.AdvertiserProfileUrl
	}
	return ""
}

func (x *Source) GetIndexedAt() string {
	if x != nil {
		return x.IndexedAt
	}
	return ""
}

func (x *Source) GetVerifiedAt() string {
	if x != nil {
		return x.VerifiedAt
	}
	return ""
}

var File_pikasa_discovery_v1_discovery_proto protoreflect.FileDescriptor

const file_pikasa_discovery_v1_discovery_proto_rawDesc = "" +
	"\n" +
	"#pikasa/discovery/v1/discovery.proto\x12\x13pikasa.discovery.v1\x1a\x1bbuf/validate/validate.proto\x1a!pikasa/listings/v1/listings.proto\"\xfd\x04\n" +
	"\x0fDiscoverRequest\x12+\n" +
	"\fcountry_code\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x02R\vcountryCode\x12\x16\n" +
	"\x06admin2\x18\x02 \x01(\tR\x06admin2\x12\"\n" +
	"\fneighborhood\x18\x03 \x01(\tR\fneighborhood\x12N\n" +
	"\x10transaction_type\x18\x04 \x01(\x0e2#.pikasa.listings.v1.TransactionTypeR\x0ftransactionType\x12\\\n" +
	"\x0eproperty_types\x18\x05 \x03(\x0e2 .pikasa.listings.v1.PropertyTypeB\x13\xbaH\x10\x92\x01\r\x10\a\x18\x01\"\a\x82\x01\x04\x10\x01 \x00R\rpropertyTypes\x12$\n" +
	"\tmin_price\x18\x06 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\bminPrice\x12$\n" +
	"\tmax_price\x18\a \x01(\x03B\a\xbaH\x04\"\x02(\x00R\bmaxPrice\x12*\n" +
	"\fmin_bedrooms\x18\b \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\vminBedrooms\x123\n" +
	"\x04bbox\x18\t \x01(\v2\x1f.pikasa.listings.v1.BoundingBoxR\x04bbox\x121\n" +
	"\x14include_developments\x18\n" +
	" \x01(\bR\x13includeDevelopments\x12&\n" +
	"\tpage_size\x18\v \x01(\x05B\t\xbaH\x06\x1a\x04\x182(\x00R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\f \x01(\tR\tpageToken\x12,\n" +
	"\x04near\x18\r \x01(\v2\x18.pikasa.listings.v1.NearR\x04near\"q\n" +
	"\x10DiscoverResponse\x125\n" +
	"\aresults\x18\x01 \x03(\v2\x1b.pikasa.discovery.v1.ResultR\aresults\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xb7\x04\n" +
	"\x06Result\x123\n" +
	"\x06source\x18\x01 \x01(\v2\x1b.pikasa.discovery.v1.SourceR\x06source\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12E\n" +
	"\rproperty_type\x18\x03 \x01(\x0e2 .pikasa.listings.v1.PropertyTypeR\fpropertyType\x128\n" +
	"\n" +
	"sale_price\x18\x04 \x01(\v2\x19.pikasa.listings.v1.MoneyR\tsalePrice\x128\n" +
	"\n" +
	"rent_price\x18\x05 \x01(\v2\x19.pikasa.listings.v1.MoneyR\trentPrice\x128\n" +
	"\blocation\x18\x06 \x01(\v2\x1c.pikasa.listings.v1.LocationR\blocation\x12!\n" +
	"\fhas_location\x18\a \x01(\bR\vhasLocation\x12\x17\n" +
	"\aarea_m2\x18\b \x01(\x01R\x06areaM2\x12\x1a\n" +
	"\bbedrooms\x18\t \x01(\x05R\bbedrooms\x12\x1c\n" +
	"\tbathrooms\x18\n" +
	" \x01(\x05R\tbathrooms\x12\x1d\n" +
	"\n" +
	"photo_urls\x18\v \x03(\tR\tphotoUrls\x12%\n" +
	"\x0eis_development\x18\f \x01(\bR\risDevelopment\x12\"\n" +
	"\n" +
	"distance_m\x18\r \x01(\x01H\x00R\tdistanceM\x88\x01\x01B\r\n" +
	"\v_distance_m\"\xcd\x01\n" +
	"\x06Source\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12'\n" +
	"\x0fadvertiser_name\x18\x03 \x01(\tR\x0eadvertiserName\x124\n" +
	"\x16advertiser_profile_url\x18\x04 \x01(\tR\x14advertiserProfileUrl\x12\x1d\n" +
	"\n" +
	"indexed_at\x18\x05 \x01(\tR\tindexedAt\x12\x1f\n" +
	"\vverified_at\x18\x06 \x01(\tR\n" +
	"verifiedAt2k\n" +
	"\x10DiscoveryService\x12W\n" +
	"\bDiscover\x12$.pikasa.discovery.v1.DiscoverRequest\x1a%.pikasa.discovery.v1.DiscoverResponseB\xd6\x01\n" +
	"\x17com.pikasa.discovery.v1B\x0eDiscoveryProtoP\x01Z=github.com/pikasaco/pikasa-go/pikasa/discovery/v1;discoveryv1\xa2\x02\x03PDX\xaa\x02\x13Pikasa.Discovery.V1\xca\x02\x13Pikasa\\Discovery\\V1\xe2\x02\x1fPikasa\\Discovery\\V1\\GPBMetadata\xea\x02\x15Pikasa::Discovery::V1b\x06proto3"

var (
	file_pikasa_discovery_v1_discovery_proto_rawDescOnce sync.Once
	file_pikasa_discovery_v1_discovery_proto_rawDescData []byte
)

func file_pikasa_discovery_v1_discovery_proto_rawDescGZIP() []byte {
	file_pikasa_discovery_v1_discovery_proto_rawDescOnce.Do(func() {
		file_pikasa_discovery_v1_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pikasa_discovery_v1_discovery_proto_rawDesc), len(file_pikasa_discovery_v1_discovery_proto_rawDesc)))
	})
	return file_pikasa_discovery_v1_discovery_proto_rawDescData
}

var file_pikasa_discovery_v1_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pikasa_discovery_v1_discovery_proto_goTypes = []any{
	(*DiscoverRequest)(nil),  // 0: pikasa.discovery.v1.DiscoverRequest
	(*DiscoverResponse)(nil), // 1: pikasa.discovery.v1.DiscoverResponse
	(*Result)(nil),           // 2: pikasa.discovery.v1.Result
	(*Source)(nil),           // 3: pikasa.discovery.v1.Source
	(v1.TransactionType)(0),  // 4: pikasa.listings.v1.TransactionType
	(v1.PropertyType)(0),     // 5: pikasa.listings.v1.PropertyType
	(*v1.BoundingBox)(nil),   // 6: pikasa.listings.v1.BoundingBox
	(*v1.Near)(nil),          // 7: pikasa.listings.v1.Near
	(*v1.Money)(nil),         // 8: pikasa.listings.v1.Money
	(*v1.Location)(nil),      // 9: pikasa.listings.v1.Location
}
var file_pikasa_discovery_v1_discovery_proto_depIdxs = []int32{
	4,  // 0: pikasa.discovery.v1.DiscoverRequest.transaction_type:type_name -> pikasa.listings.v1.TransactionType
	5,  // 1: pikasa.discovery.v1.DiscoverRequest.property_types:type_name -> pikasa.listings.v1.PropertyType
	6,  // 2: pikasa.discovery.v1.DiscoverRequest.bbox:type_name -> pikasa.listings.v1.BoundingBox
	7,  // 3: pikasa.discovery.v1.DiscoverRequest.near:type_name -> pikasa.listings.v1.Near
	2,  // 4: pikasa.discovery.v1.DiscoverResponse.results:type_name -> pikasa.discovery.v1.Result
	3,  // 5: pikasa.discovery.v1.Result.source:type_name -> pikasa.discovery.v1.Source
	5,  // 6: pikasa.discovery.v1.Result.property_type:type_name -> pikasa.listings.v1.PropertyType
	8,  // 7: pikasa.discovery.v1.Result.sale_price:type_name -> pikasa.listings.v1.Money
	8,  // 8: pikasa.discovery.v1.Result.rent_price:type_name -> pikasa.listings.v1.Money
	9,  // 9: pikasa.discovery.v1.Result.location:type_name -> pikasa.listings.v1.Location
	0,  // 10: pikasa.discovery.v1.DiscoveryService.Discover:input_type -> pikasa.discovery.v1.DiscoverRequest
	1,  // 11: pikasa.discovery.v1.DiscoveryService.Discover:output_type -> pikasa.discovery.v1.DiscoverResponse
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pikasa_discovery_v1_discovery_proto_init() }
func file_pikasa_discovery_v1_discovery_proto_init() {
	if File_pikasa_discovery_v1_discovery_proto != nil {
		return
	}
	file_pikasa_discovery_v1_discovery_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pikasa_discovery_v1_discovery_proto_rawDesc), len(file_pikasa_discovery_v1_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pikasa_discovery_v1_discovery_proto_goTypes,
		DependencyIndexes: file_pikasa_discovery_v1_discovery_proto_depIdxs,
		MessageInfos:      file_pikasa_discovery_v1_discovery_proto_msgTypes,
	}.Build()
	File_pikasa_discovery_v1_discovery_proto = out.File
	file_pikasa_discovery_v1_discovery_proto_goTypes = nil
	file_pikasa_discovery_v1_discovery_proto_depIdxs = nil
}
