// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pikasa/integrators/v1/integrators.proto

package integratorsv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/pikasaco/pikasa-go/pikasa/listings/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpsertOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          v1.OrganizationType    `protobuf:"varint,3,opt,name=type,proto3,enum=pikasa.listings.v1.OrganizationType" json:"type,omitempty"`
	LogoUrl       string                 `protobuf:"bytes,4,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Whatsapp      string                 `protobuf:"bytes,6,opt,name=whatsapp,proto3" json:"whatsapp,omitempty"`
	Email         string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Website       string                 `protobuf:"bytes,8,opt,name=website,proto3" json:"website,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertOrganizationRequest) Reset() {
	*x = UpsertOrganizationRequest{}
	mi := &file_pikasa_integrators_v1_integrators_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertOrganizationRequest) ProtoMessage() {}

func (x *UpsertOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_integrators_v1_integrators_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertOrganizationRequest.ProtoReflect.Descriptor instead.
func (*UpsertOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_pikasa_integrators_v1_integrators_proto_rawDescGZIP(), []int{0}
}

func (x *UpsertOrganizationRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *UpsertOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpsertOrganizationRequest) GetType() v1.OrganizationType {
	if x != nil {
		return x.Type
	}
	return v1.OrganizationType(0)
}

func (x *UpsertOrganizationRequest) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *UpsertOrganizationRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpsertOrganizationRequest) GetWhatsapp() string {
	if x != nil {
		return x.Whatsapp
	}
	return ""
}

func (x *UpsertOrganizationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpsertOrganizationRequest) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

type UpsertOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicId      string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertOrganizationResponse) Reset() {
	*x = UpsertOrganizationResponse{}
	mi := &file_pikasa_integrators_v1_integrators_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertOrganizationResponse) ProtoMessage() {}

func (x *UpsertOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_integrators_v1_integrators_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertOrganizationResponse.ProtoReflect.Descriptor instead.
func (*UpsertOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_pikasa_integrators_v1_integrators_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertOrganizationResponse) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

type AgentContact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Whatsapp      string                 `protobuf:"bytes,3,opt,name=whatsapp,proto3" json:"whatsapp,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentContact) Reset() {
	*x = AgentContact{}
	mi := &file_pikasa_integrators_v1_integrators_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentContact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentContact) ProtoMessage() {}

func (x *AgentContact) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_integrators_v1_integrators_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentContact.ProtoReflect.Descriptor instead.
func (*AgentContact) Descriptor() ([]byte, []int) {
	return file_pikasa_integrators_v1_integrators_proto_rawDescGZIP(), []int{2}
}

func (x *AgentContact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentContact) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *AgentContact) GetWhatsapp() string {
	if x != nil {
		return x.Whatsapp
	}
	return ""
}

func (x *AgentContact) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UpsertListingRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ExternalId string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	// external_id of a previously-upserted organization of this integrator.
	OrganizationExternalId string             `protobuf:"bytes,2,opt,name=organization_external_id,json=organizationExternalId,proto3" json:"organization_external_id,omitempty"`
	Title                  string             `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description            string             `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	PropertyType           v1.PropertyType    `protobuf:"varint,5,opt,name=property_type,json=propertyType,proto3,enum=pikasa.listings.v1.PropertyType" json:"property_type,omitempty"`
	TransactionType        v1.TransactionType `protobuf:"varint,6,opt,name=transaction_type,json=transactionType,proto3,enum=pikasa.listings.v1.TransactionType" json:"transaction_type,omitempty"`
	Price                  *v1.Price          `protobuf:"bytes,7,opt,name=price,proto3" json:"price,omitempty"`
	Location               *v1.Location       `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	Specs                  *v1.Specs          `protobuf:"bytes,9,opt,name=specs,proto3" json:"specs,omitempty"`
	Amenities              []string           `protobuf:"bytes,10,rep,name=amenities,proto3" json:"amenities,omitempty"`
	Photos                 []*v1.Photo        `protobuf:"bytes,11,rep,name=photos,proto3" json:"photos,omitempty"`
	CountryFields          map[string]string  `protobuf:"bytes,12,rep,name=country_fields,json=countryFields,proto3" json:"country_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Agent                  *AgentContact      `protobuf:"bytes,13,opt,name=agent,proto3" json:"agent,omitempty"`
	// active|paused — removal goes through RemoveListing.
	Status        v1.ListingStatus `protobuf:"varint,14,opt,name=status,proto3,enum=pikasa.listings.v1.ListingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertListingRequest) Reset() {
	*x = UpsertListingRequest{}
	mi := &file_pikasa_integrators_v1_integrators_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertListingRequest) ProtoMessage() {}

func (x *UpsertListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_integrators_v1_integrators_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertListingRequest.ProtoReflect.Descriptor instead.
func (*UpsertListingRequest) Descriptor() ([]byte, []int) {
	return file_pikasa_integrators_v1_integrators_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertListingRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *UpsertListingRequest) GetOrganizationExternalId() string {
	if x != nil {
		return x.OrganizationExternalId
	}
	return ""
}

func (x *UpsertListingRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpsertListingRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpsertListingRequest) GetPropertyType() v1.PropertyType {
	if x != nil {
		return x.PropertyType
	}
	return v1.PropertyType(0)
}

func (x *UpsertListingRequest) GetTransactionType() v1.TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return v1.TransactionType(0)
}

func (x *UpsertListingRequest) GetPrice() *v1.Price {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *UpsertListingRequest) GetLocation() *v1.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *UpsertListingRequest) GetSpecs() *v1.Specs {
	if x != nil {
		return x.Specs
	}
	return nil
}

func (x *UpsertListingRequest) GetAmenities() []string {
	if x != nil {
		return x.Amenities
	}
	return nil
}

func (x *UpsertListingRequest) GetPhotos() []*v1.Photo {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *UpsertListingRequest) GetCountryFields() map[string]string {
	if x != nil {
		return x.CountryFields
	}
	return nil
}

func (x *UpsertListingRequest) GetAgent() *AgentContact {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *UpsertListingRequest) GetStatus() v1.ListingStatus {
	if x != nil {
		return x.Status
	}
	return v1.ListingStatus(0)
}

type UpsertListingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicId      string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertListingResponse) Reset() {
	*x = UpsertListingResponse{}
	mi := &file_pikasa_integrators_v1_integrators_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertListingResponse) ProtoMessage() {}

func (x *UpsertListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_integrators_v1_integrators_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertListingResponse.ProtoReflect.Descriptor instead.
func (*UpsertListingResponse) Descriptor() ([]byte, []int) {
	return file_pikasa_integrators_v1_integrators_proto_rawDescGZIP(), []int{4}
}

func (x *UpsertListingResponse) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

type RemoveListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveListingRequest) Reset() {
	*x = RemoveListingRequest{}
	mi := &file_pikasa_integrators_v1_integrators_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveListingRequest) ProtoMessage() {}

func (x *RemoveListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_integrators_v1_integrators_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveListingRequest.ProtoReflect.Descriptor instead.
func (*RemoveListingRequest) Descriptor() ([]byte, []int) {
	return file_pikasa_integrators_v1_integrators_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveListingRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

type RemoveListingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveListingResponse) Reset() {
	*x = RemoveListingResponse{}
	mi := &file_pikasa_integrators_v1_integrators_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveListingResponse) ProtoMessage() {}

func (x *RemoveListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_integrators_v1_integrators_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveListingResponse.ProtoReflect.Descriptor instead.
func (*RemoveListingResponse) Descriptor() ([]byte, []int) {
	return file_pikasa_integrators_v1_integrators_proto_rawDescGZIP(), []int{6}
}

type SetWebhookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endpoint that receives lead webhooks (POST, JSON). Empty clears the
	// configuration and disables webhook delivery (leads fall back to email).
	Url           string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWebhookRequest) Reset() {
	*x = SetWebhookRequest{}
	mi := &file_pikasa_integrators_v1_integrators_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWebhookRequest) ProtoMessage() {}

func (x *SetWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_integrators_v1_integrators_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWebhookRequest.ProtoReflect.Descriptor instead.
func (*SetWebhookRequest) Descriptor() ([]byte, []int) {
	return file_pikasa_integrators_v1_integrators_proto_rawDescGZIP(), []int{7}
}

func (x *SetWebhookRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SetWebhookResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Signing secret (whsec_<hex>), shown once. Every delivery carries
	// X-Pikasa-Timestamp (unix seconds) and X-Pikasa-Signature =
	// hex(HMAC-SHA256(timestamp + "." + raw_body, secret)). Receivers should
	// reject stale timestamps (e.g. > 5 minutes) to prevent replay, and must
	// dedup on the payload's leadId (delivery is at-least-once).
	// Empty when the request cleared the webhook.
	Secret        string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWebhookResponse) Reset() {
	*x = SetWebhookResponse{}
	mi := &file_pikasa_integrators_v1_integrators_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWebhookResponse) ProtoMessage() {}

func (x *SetWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_integrators_v1_integrators_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWebhookResponse.ProtoReflect.Descriptor instead.
func (*SetWebhookResponse) Descriptor() ([]byte, []int) {
	return file_pikasa_integrators_v1_integrators_proto_rawDescGZIP(), []int{8}
}

func (x *SetWebhookResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

var File_pikasa_integrators_v1_integrators_proto protoreflect.FileDescriptor

const file_pikasa_integrators_v1_integrators_proto_rawDesc = "" +
	"\n" +
	"'pikasa/integrators/v1/integrators.proto\x12\x15pikasa.integrators.v1\x1a\x1bbuf/validate/validate.proto\x1a!pikasa/listings/v1/listings.proto\"\x99\x02\n" +
	"\x19UpsertOrganizationRequest\x12(\n" +
	"\vexternal_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"externalId\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x128\n" +
	"\x04type\x18\x03 \x01(\x0e2$.pikasa.listings.v1.OrganizationTypeR\x04type\x12\x19\n" +
	"\blogo_url\x18\x04 \x01(\tR\alogoUrl\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x1a\n" +
	"\bwhatsapp\x18\x06 \x01(\tR\bwhatsapp\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12\x18\n" +
	"\awebsite\x18\b \x01(\tR\awebsite\"9\n" +
	"\x1aUpsertOrganizationResponse\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\"j\n" +
	"\fAgentContact\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x1a\n" +
	"\bwhatsapp\x18\x03 \x01(\tR\bwhatsapp\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"\xe7\x06\n" +
	"\x14UpsertListingRequest\x12(\n" +
	"\vexternal_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"externalId\x12A\n" +
	"\x18organization_external_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x16organizationExternalId\x12\x1d\n" +
	"\x05title\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12E\n" +
	"\rproperty_type\x18\x05 \x01(\x0e2 .pikasa.listings.v1.PropertyTypeR\fpropertyType\x12N\n" +
	"\x10transaction_type\x18\x06 \x01(\x0e2#.pikasa.listings.v1.TransactionTypeR\x0ftransactionType\x12/\n" +
	"\x05price\x18\a \x01(\v2\x19.pikasa.listings.v1.PriceR\x05price\x128\n" +
	"\blocation\x18\b \x01(\v2\x1c.pikasa.listings.v1.LocationR\blocation\x12/\n" +
	"\x05specs\x18\t \x01(\v2\x19.pikasa.listings.v1.SpecsR\x05specs\x12\x1c\n" +
	"\tamenities\x18\n" +
	" \x03(\tR\tamenities\x121\n" +
	"\x06photos\x18\v \x03(\v2\x19.pikasa.listings.v1.PhotoR\x06photos\x12e\n" +
	"\x0ecountry_fields\x18\f \x03(\v2>.pikasa.integrators.v1.UpsertListingRequest.CountryFieldsEntryR\rcountryFields\x129\n" +
	"\x05agent\x18\r \x01(\v2#.pikasa.integrators.v1.AgentContactR\x05agent\x129\n" +
	"\x06status\x18\x0e \x01(\x0e2!.pikasa.listings.v1.ListingStatusR\x06status\x1a@\n" +
	"\x12CountryFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\x15UpsertListingResponse\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\"@\n" +
	"\x14RemoveListingRequest\x12(\n" +
	"\vexternal_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"externalId\"\x17\n" +
	"\x15RemoveListingResponse\"/\n" +
	"\x11SetWebhookRequest\x12\x1a\n" +
	"\x03url\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x18\xf4\x03R\x03url\",\n" +
	"\x12SetWebhookResponse\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret2\xc9\x03\n" +
	"\x11IntegratorService\x12y\n" +
	"\x12UpsertOrganization\x120.pikasa.integrators.v1.UpsertOrganizationRequest\x1a1.pikasa.integrators.v1.UpsertOrganizationResponse\x12j\n" +
	"\rUpsertListing\x12+.pikasa.integrators.v1.UpsertListingRequest\x1a,.pikasa.integrators.v1.UpsertListingResponse\x12j\n" +
	"\rRemoveListing\x12+.pikasa.integrators.v1.RemoveListingRequest\x1a,.pikasa.integrators.v1.RemoveListingResponse\x12a\n" +
	"\n" +
	"SetWebhook\x12(.pikasa.integrators.v1.SetWebhookRequest\x1a).pikasa.integrators.v1.SetWebhookResponseB\xe6\x01\n" +
	"\x19com.pikasa.integrators.v1B\x10IntegratorsProtoP\x01ZAgithub.com/pikasaco/pikasa-go/pikasa/integrators/v1;integratorsv1\xa2\x02\x03PIX\xaa\x02\x15Pikasa.Integrators.V1\xca\x02\x15Pikasa\\Integrators\\V1\xe2\x02!Pikasa\\Integrators\\V1\\GPBMetadata\xea\x02\x17Pikasa::Integrators::V1b\x06proto3"

var (
	file_pikasa_integrators_v1_integrators_proto_rawDescOnce sync.Once
	file_pikasa_integrators_v1_integrators_proto_rawDescData []byte
)

func file_pikasa_integrators_v1_integrators_proto_rawDescGZIP() []byte {
	file_pikasa_integrators_v1_integrators_proto_rawDescOnce.Do(func() {
		file_pikasa_integrators_v1_integrators_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pikasa_integrators_v1_integrators_proto_rawDesc), len(file_pikasa_integrators_v1_integrators_proto_rawDesc)))
	})
	return file_pikasa_integrators_v1_integrators_proto_rawDescData
}

var file_pikasa_integrators_v1_integrators_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pikasa_integrators_v1_integrators_proto_goTypes = []any{
	(*UpsertOrganizationRequest)(nil),  // 0: pikasa.integrators.v1.UpsertOrganizationRequest
	(*UpsertOrganizationResponse)(nil), // 1: pikasa.integrators.v1.UpsertOrganizationResponse
	(*AgentContact)(nil),               // 2: pikasa.integrators.v1.AgentContact
	(*UpsertListingRequest)(nil),       // 3: pikasa.integrators.v1.UpsertListingRequest
	(*UpsertListingResponse)(nil),      // 4: pikasa.integrators.v1.UpsertListingResponse
	(*RemoveListingRequest)(nil),       // 5: pikasa.integrators.v1.RemoveListingRequest
	(*RemoveListingResponse)(nil),      // 6: pikasa.integrators.v1.RemoveListingResponse
	(*SetWebhookRequest)(nil),          // 7: pikasa.integrators.v1.SetWebhookRequest
	(*SetWebhookResponse)(nil),         // 8: pikasa.integrators.v1.SetWebhookResponse
	nil,                                // 9: pikasa.integrators.v1.UpsertListingRequest.CountryFieldsEntry
	(v1.OrganizationType)(0),           // 10: pikasa.listings.v1.OrganizationType
	(v1.PropertyType)(0),               // 11: pikasa.listings.v1.PropertyType
	(v1.TransactionType)(0),            // 12: pikasa.listings.v1.TransactionType
	(*v1.Price)(nil),                   // 13: pikasa.listings.v1.Price
	(*v1.Location)(nil),                // 14: pikasa.listings.v1.Location
	(*v1.Specs)(nil),                   // 15: pikasa.listings.v1.Specs
	(*v1.Photo)(nil),                   // 16: pikasa.listings.v1.Photo
	(v1.ListingStatus)(0),              // 17: pikasa.listings.v1.ListingStatus
}
var file_pikasa_integrators_v1_integrators_proto_depIdxs = []int32{
	10, // 0: pikasa.integrators.v1.UpsertOrganizationRequest.type:type_name -> pikasa.listings.v1.OrganizationType
	11, // 1: pikasa.integrators.v1.UpsertListingRequest.property_type:type_name -> pikasa.listings.v1.PropertyType
	12, // 2: pikasa.integrators.v1.UpsertListingRequest.transaction_type:type_name -> pikasa.listings.v1.TransactionType
	13, // 3: pikasa.integrators.v1.UpsertListingRequest.price:type_name -> pikasa.listings.v1.Price
	14, // 4: pikasa.integrators.v1.UpsertListingRequest.location:type_name -> pikasa.listings.v1.Location
	15, // 5: pikasa.integrators.v1.UpsertListingRequest.specs:type_name -> pikasa.listings.v1.Specs
	16, // 6: pikasa.integrators.v1.UpsertListingRequest.photos:type_name -> pikasa.listings.v1.Photo
	9,  // 7: pikasa.integrators.v1.UpsertListingRequest.country_fields:type_name -> pikasa.integrators.v1.UpsertListingRequest.CountryFieldsEntry
	2,  // 8: pikasa.integrators.v1.UpsertListingRequest.agent:type_name -> pikasa.integrators.v1.AgentContact
	17, // 9: pikasa.integrators.v1.UpsertListingRequest.status:type_name -> pikasa.listings.v1.ListingStatus
	0,  // 10: pikasa.integrators.v1.IntegratorService.UpsertOrganization:input_type -> pikasa.integrators.v1.UpsertOrganizationRequest
	3,  // 11: pikasa.integrators.v1.IntegratorService.UpsertListing:input_type -> pikasa.integrators.v1.UpsertListingRequest
	5,  // 12: pikasa.integrators.v1.IntegratorService.RemoveListing:input_type -> pikasa.integrators.v1.RemoveListingRequest
	7,  // 13: pikasa.integrators.v1.IntegratorService.SetWebhook:input_type -> pikasa.integrators.v1.SetWebhookRequest
	1,  // 14: pikasa.integrators.v1.IntegratorService.UpsertOrganization:output_type -> pikasa.integrators.v1.UpsertOrganizationResponse
	4,  // 15: pikasa.integrators.v1.IntegratorService.UpsertListing:output_type -> pikasa.integrators.v1.UpsertListingResponse
	6,  // 16: pikasa.integrators.v1.IntegratorService.RemoveListing:output_type -> pikasa.integrators.v1.RemoveListingResponse
	8,  // 17: pikasa.integrators.v1.IntegratorService.SetWebhook:output_type -> pikasa.integrators.v1.SetWebhookResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pikasa_integrators_v1_integrators_proto_init() }
func file_pikasa_integrators_v1_integrators_proto_init() {
	if File_pikasa_integrators_v1_integrators_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pikasa_integrators_v1_integrators_proto_rawDesc), len(file_pikasa_integrators_v1_integrators_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pikasa_integrators_v1_integrators_proto_goTypes,
		DependencyIndexes: file_pikasa_integrators_v1_integrators_proto_depIdxs,
		MessageInfos:      file_pikasa_integrators_v1_integrators_proto_msgTypes,
	}.Build()
	File_pikasa_integrators_v1_integrators_proto = out.File
	file_pikasa_integrators_v1_integrators_proto_goTypes = nil
	file_pikasa_integrators_v1_integrators_proto_depIdxs = nil
}
