// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pikasa/leads/v1/leads.proto

package leadsv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLeadRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ListingPublicId string                 `protobuf:"bytes,1,opt,name=listing_public_id,json=listingPublicId,proto3" json:"listing_public_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email           string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone           string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Message         string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateLeadRequest) Reset() {
	*x = CreateLeadRequest{}
	mi := &file_pikasa_leads_v1_leads_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLeadRequest) ProtoMessage() {}

func (x *CreateLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_leads_v1_leads_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLeadRequest.ProtoReflect.Descriptor instead.
func (*CreateLeadRequest) Descriptor() ([]byte, []int) {
	return file_pikasa_leads_v1_leads_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLeadRequest) GetListingPublicId() string {
	if x != nil {
		return x.ListingPublicId
	}
	return ""
}

func (x *CreateLeadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateLeadRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateLeadRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateLeadRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateLeadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeadId        string                 `protobuf:"bytes,1,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLeadResponse) Reset() {
	*x = CreateLeadResponse{}
	mi := &file_pikasa_leads_v1_leads_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLeadResponse) ProtoMessage() {}

func (x *CreateLeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pikasa_leads_v1_leads_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLeadResponse.ProtoReflect.Descriptor instead.
func (*CreateLeadResponse) Descriptor() ([]byte, []int) {
	return file_pikasa_leads_v1_leads_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLeadResponse) GetLeadId() string {
	if x != nil {
		return x.LeadId
	}
	return ""
}

var File_pikasa_leads_v1_leads_proto protoreflect.FileDescriptor

const file_pikasa_leads_v1_leads_proto_rawDesc = "" +
	"\n" +
	"\x1bpikasa/leads/v1/leads.proto\x12\x0fpikasa.leads.v1\x1a\x1bbuf/validate/validate.proto\"\xcc\x01\n" +
	"\x11CreateLeadRequest\x123\n" +
	"\x11listing_public_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0flistingPublicId\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18xR\x04name\x12 \n" +
	"\x05email\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x03\x18\xfe\x01R\x05email\x12\x1d\n" +
	"\x05phone\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x18 R\x05phone\x12\"\n" +
	"\amessage\x18\x05 \x01(\tB\b\xbaH\x05r\x03\x18\xd0\x0fR\amessage\"-\n" +
	"\x12CreateLeadResponse\x12\x17\n" +
	"\alead_id\x18\x01 \x01(\tR\x06leadId2e\n" +
	"\fLeadsService\x12U\n" +
	"\n" +
	"CreateLead\x12\".pikasa.leads.v1.CreateLeadRequest\x1a#.pikasa.leads.v1.CreateLeadResponseB\xb6\x01\n" +
	"\x13com.pikasa.leads.v1B\n" +
	"LeadsProtoP\x01Z5github.com/pikasaco/pikasa-go/pikasa/leads/v1;leadsv1\xa2\x02\x03PLX\xaa\x02\x0fPikasa.Leads.V1\xca\x02\x0fPikasa\\Leads\\V1\xe2\x02\x1bPikasa\\Leads\\V1\\GPBMetadata\xea\x02\x11Pikasa::Leads::V1b\x06proto3"

var (
	file_pikasa_leads_v1_leads_proto_rawDescOnce sync.Once
	file_pikasa_leads_v1_leads_proto_rawDescData []byte
)

func file_pikasa_leads_v1_leads_proto_rawDescGZIP() []byte {
	file_pikasa_leads_v1_leads_proto_rawDescOnce.Do(func() {
		file_pikasa_leads_v1_leads_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pikasa_leads_v1_leads_proto_rawDesc), len(file_pikasa_leads_v1_leads_proto_rawDesc)))
	})
	return file_pikasa_leads_v1_leads_proto_rawDescData
}

var file_pikasa_leads_v1_leads_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pikasa_leads_v1_leads_proto_goTypes = []any{
	(*CreateLeadRequest)(nil),  // 0: pikasa.leads.v1.CreateLeadRequest
	(*CreateLeadResponse)(nil), // 1: pikasa.leads.v1.CreateLeadResponse
}
var file_pikasa_leads_v1_leads_proto_depIdxs = []int32{
	0, // 0: pikasa.leads.v1.LeadsService.CreateLead:input_type -> pikasa.leads.v1.CreateLeadRequest
	1, // 1: pikasa.leads.v1.LeadsService.CreateLead:output_type -> pikasa.leads.v1.CreateLeadResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pikasa_leads_v1_leads_proto_init() }
func file_pikasa_leads_v1_leads_proto_init() {
	if File_pikasa_leads_v1_leads_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pikasa_leads_v1_leads_proto_rawDesc), len(file_pikasa_leads_v1_leads_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pikasa_leads_v1_leads_proto_goTypes,
		DependencyIndexes: file_pikasa_leads_v1_leads_proto_depIdxs,
		MessageInfos:      file_pikasa_leads_v1_leads_proto_msgTypes,
	}.Build()
	File_pikasa_leads_v1_leads_proto = out.File
	file_pikasa_leads_v1_leads_proto_goTypes = nil
	file_pikasa_leads_v1_leads_proto_depIdxs = nil
}
